### ISSUE TITLE
BE core when load_index

### ISSUE THREAD

**Issue by kangkaisen** [apache/incubator-doris#1124]
**Describe the bug**

```
*** Aborted at 1557246373 (unix time) try "date -d @1557246373" if you are using GNU date ***
PC: @           0xd2c20a doris::ShardedLRUCache::lookup()
*** SIGSEGV (@0x0) received by PID 15309 (TID 0x7f9b8a9ae700) from PID 0; stack trace: ***
    @     0x7f9b9562c2f0 (unknown)
    @           0xd2c20a doris::ShardedLRUCache::lookup()
    @           0xd669b4 doris::column_file::SegmentReader::_load_index()
    @           0xd6b5dc doris::column_file::SegmentReader::init()
    @           0xd4941a doris::column_file::ColumnData::_seek_to_block()
    @           0xd4c263 doris::column_file::ColumnData::prepare_block_read()
    @           0xcb7e48 doris::Reader::_attach_data_to_merge_set()
    @           0xcbb136 doris::Reader::init()
    @           0xd2deb2 doris::Merger::merge()
    @           0xd1943d doris::CumulativeCompaction::_do_cumulative_compaction()
    @           0xd19f95 doris::CumulativeCompaction::run()
    @           0xc5f796 doris::OLAPEngine::perform_cumulative_compaction()
    @           0xc83337 doris::OLAPEngine::_cumulative_compaction_thread_callback()
    @           0xc833df _ZNSt6thread11_State_implINS_8_InvokerISt5tupleIJZN5doris10OLAPEngine16_start_bg_workerEvEUlvE3_EEEEE6_M_runEv
    @          0x2526acf execute_native_thread_routine
    @     0x7f9b953e1e25 start_thread
    @     0x7f9b956f4bad __clone


 #0  0x0000000000d2c20a in _find_pointer (hash=2483700659, key=..., this=0x6fc6948)
    at /home/kangkaisen/palo/be/src/olap/lru_cache.cpp:122
#1  lookup (hash=<optimized out>, key=..., this=0x6fc6948) at /home/kangkaisen/palo/be/src/olap/lru_cache.cpp:83
#2  lookup (hash=<optimized out>, key=..., this=0x6fc6878) at /home/kangkaisen/palo/be/src/olap/lru_cache.cpp:239
#3  doris::ShardedLRUCache::lookup (this=0x6fc6000, key=...) at /home/kangkaisen/palo/be/src/olap/lru_cache.cpp:351
#4  0x0000000000d669b4 in doris::column_file::SegmentReader::_load_index (this=this@entry=0x228b07400,
    is_using_cache=is_using_cache@entry=false) at /home/kangkaisen/palo/be/src/olap/column_file/segment_reader.cpp:638
#5  0x0000000000d6b5dc in doris::column_file::SegmentReader::init (this=this@entry=0x228b07400, is_using_cache=<optimized out>)
    at /home/kangkaisen/palo/be/src/olap/column_file/segment_reader.cpp:232
#6  0x0000000000d4941a in doris::column_file::ColumnData::_seek_to_block (this=this@entry=0xee9ee600, block_pos=...,
    without_filter=without_filter@entry=false) at /home/kangkaisen/palo/be/src/olap/column_file/column_data.cpp:130
#7  0x0000000000d4c263 in doris::column_file::ColumnData::prepare_block_read (this=0xee9ee600, start_key=0x0,
    find_start_key=<optimized out>, end_key=0x0, find_end_key=<optimized out>, first_block=0x7f9b8a9807e0)
    at /home/kangkaisen/palo/be/src/olap/column_file/column_data.cpp:379



(gdb) p cache_handle_index
$1 = 87

$2 = {_data = 0x7f9b8a9789c0 "/data8/olap/data/485/116765099/2133058311/116765099_6135_6135_6110004576278746592_0_0.datW",
  _size = 97}

(gdb) p _length
$11 = 262144

(gdb) p hash
$7 = 2483700659


(gdb) p sizeof(key_buf)
$21 = 1024
(gdb) p OLAP_LRU_CACHE_MAX_KEY_LENTH
$22 = 1024

(gdb) p key_buf
$23 = "/data8/olap/data/485/116765099/2133058311/116765099_6135_6135_6110004576278746592_0_0.datW\000\000\000\000\000\000\000\212\227\212\233\177\000\000\000\240;~\036\000\000\000/\000\000\000\000\000\000\000\003\000\000\000\000\000\000\000\200\264\227\212\233\177\000\000\353,\330\000\000\000\000\000\035\000\000\000\000\000\000\000;\000\000\000\000\000\000\000\200\264\227\212\233\177\000\000r,\330\000\000\000\000\000\n\000\000\000\000\000\000\000=\000\000\000\000\000\000\000&\000\000\000\000\000\000\000"...

(gdb) p _file_handler
$24 = {_fd = 8687, _wr_length = 0, _cache_threshold = 524288, _file_name = {static npos = 18446744073709551615,
    _M_dataplus = {<std::allocator<char>> = {<__gnu_cxx::new_allocator<char>> = {<No data fields>}, <No data fields>},
      _M_p = 0x47ab59e60 "/data8/olap/data/485/116765099/2133058311/116765099_6135_6135_6110004576278746592_0_0.dat"},
    _M_string_length = 89, {_M_local_buf = "Y\000\000\000\000\000\000\000\004\000\000\000\000\000\000",
      _M_allocated_capacity = 89}}, _is_using_cache = true, _cache_handle = 0x7a52ca00}
```

**Comment by kangpinghuang** [comment]
what is the code base?
it seems that is different from:
commit ae8d16c81e47930ae0f1fb0c31d35dcfe9f337dc
Author: chenhao7253886 <510341142@qq.com>
Date:   Mon Nov 12 11:15:39 2018 +0800

    Fix failed cases in regression test (#299)

**Comment by kangkaisen** [comment]
I have cherry-picked some commit from master.

We can ignore this issue tentatively.

I will upgrade to 0.10 version when which release. If this issue happen on 0.10 version again, we could deep into this issue together.

**Comment by kangpinghuang** [comment]
ok
