### ISSUE TITLE
Follower FE restart failed 

### ISSUE THREAD

**Issue by morningman** [apache/incubator-doris#1362]
**Describe the bug**
Restore a follower FE, throw exception:

2019-06-23 17:49:06,546 ERROR 1 [BDBEnvironment.setup():195] error to open replicated environment. will exit.
com.sleepycat.je.EnvironmentFailureException: Environment invalid because of previous exception: (JE 7.3.7) 10.227.96.25_9110_1557800838823(-1):/
home/palo/palo/fe/palo-meta/bdb recoveryTracker should overlap or follow on disk last VLSN of 99,937,900 recoveryFirst= 99,937,902 UNEXPECTED
_STATE_FATAL: Unexpected internal state, unable to continue. Environment is invalid and must be closed.
        at com.sleepycat.je.EnvironmentFailureException.unexpectedState(EnvironmentFailureException.java:443) ~[je-7.3.7.jar:7.3.7]
        at com.sleepycat.je.rep.vlsn.VLSNIndex.merge(VLSNIndex.java:1573) ~[je-7.3.7.jar:7.3.7]
        at com.sleepycat.je.rep.vlsn.VLSNIndex.init(VLSNIndex.java:1483) ~[je-7.3.7.jar:7.3.7]
        at com.sleepycat.je.rep.vlsn.VLSNIndex.<init>(VLSNIndex.java:422) ~[je-7.3.7.jar:7.3.7]
        at com.sleepycat.je.rep.impl.RepImpl.preRecoveryCheckpointInit(RepImpl.java:567) ~[je-7.3.7.jar:7.3.7]
        at com.sleepycat.je.recovery.RecoveryManager.recover(RecoveryManager.java:461) ~[je-7.3.7.jar:7.3.7]
        at com.sleepycat.je.dbi.EnvironmentImpl.finishInit(EnvironmentImpl.java:841) ~[je-7.3.7.jar:7.3.7]
        at com.sleepycat.je.dbi.DbEnvPool.getEnvironment(DbEnvPool.java:222) ~[je-7.3.7.jar:7.3.7]
        at com.sleepycat.je.Environment.makeEnvironmentImpl(Environment.java:267) ~[je-7.3.7.jar:7.3.7]
        at com.sleepycat.je.Environment.<init>(Environment.java:252) ~[je-7.3.7.jar:7.3.7]
        at com.sleepycat.je.rep.ReplicatedEnvironment.<init>(ReplicatedEnvironment.java:607) ~[je-7.3.7.jar:7.3.7]
        at com.sleepycat.je.rep.ReplicatedEnvironment.<init>(ReplicatedEnvironment.java:466) ~[je-7.3.7.jar:7.3.7]
        at com.sleepycat.je.rep.ReplicatedEnvironment.<init>(ReplicatedEnvironment.java:540) ~[je-7.3.7.jar:7.3.7]
        at org.apache.doris.journal.bdbje.BDBEnvironment.setup(BDBEnvironment.java:146) [palo-fe.jar:?]
        at org.apache.doris.journal.bdbje.BDBJEJournal.open(BDBJEJournal.java:313) [palo-fe.jar:?]
        at org.apache.doris.persist.EditLog.open(EditLog.java:719) [palo-fe.jar:?]
        at org.apache.doris.catalog.Catalog.initialize(Catalog.java:645) [palo-fe.jar:?]
        at org.apache.doris.service.FeServer.setup(FeServer.java:44) [palo-fe.jar:?]
        at org.apache.doris.PaloFe.main(PaloFe.java:102) [palo-fe.jar:?]

After clean the palo-meta/ dir and start with --helper again, it becomes normal.

**Comment by morningman** [comment]
https://community.oracle.com/thread/2197232?tstart=0

**Comment by EmmyMiao87** [comment]
This is a bdbje bug.
The solution is following:
clean the palo-meta/ dir 
start with --helper again
it becomes normal.

**Comment by huozhanfeng** [comment]
Is it fixed by Doris now?  The issue happened in our prod cluster today. The Doris version is DORIS-0.12.21-release.

**Comment by morningman** [comment]
> Is it fixed by Doris now? The issue happened in our prod cluster today. The Doris version is DORIS-0.12.21-release.

no，but it can be recovered by setting metadata_failure_recovery=true

**Comment by huozhanfeng** [comment]
Got it, thanks.

**Comment by huozhanfeng** [comment]
> > Is it fixed by Doris now? The issue happened in our prod cluster today. The Doris version is DORIS-0.12.21-release.
> 
> no，but it can be recovered by setting metadata_failure_recovery=true

hello, I have tried it, but it doesn't work. The FE instance still failed to start after setting the conf metadata_failure_recovery=true.
