### ISSUE TITLE
function greatest do not work for date type

### ISSUE THREAD

**Issue by imay** [apache/incubator-doris#2017]
**Describe the bug**

```
mysql> select greatest(cast("2010-10-11" as date), k10) from baseall;
ERROR 1064 (HY000): Unexpected exception: null
```

**To Reproduce**

```
select greatest(cast("2010-10-11" as date), k10) from baseall;
```

where `k10` is date column.

**Expected behavior**

**Screenshots**
```
2019-10-20 13:00:06,405 WARN 2172 [StmtExecutor.analyze():465] Analyze failed because
java.lang.IllegalStateException
        at com.google.common.base.Preconditions.checkState(Preconditions.java:161) ~[jprotobuf-2.2.11-jar-with-dependencies.jar:?]
        at org.apache.doris.analysis.DateLiteral.uncheckedCastTo(DateLiteral.java:317) ~[palo-fe.jar:?]
        at org.apache.doris.analysis.Expr.uncheckedCastChild(Expr.java:1248) ~[palo-fe.jar:?]
        at org.apache.doris.analysis.FunctionCallExpr.analyzeImpl(FunctionCallExpr.java:606) ~[palo-fe.jar:?]
        at org.apache.doris.analysis.Expr.analyze(Expr.java:364) ~[palo-fe.jar:?]
        at org.apache.doris.analysis.SelectStmt.analyze(SelectStmt.java:306) ~[palo-fe.jar:?]
        at org.apache.doris.qe.StmtExecutor.analyze(StmtExecutor.java:438) [palo-fe.jar:?]
        at org.apache.doris.qe.StmtExecutor.execute(StmtExecutor.java:213) [palo-fe.jar:?]
        at org.apache.doris.qe.ConnectProcessor.handleQuery(ConnectProcessor.java:168) [palo-fe.jar:?]
        at org.apache.doris.qe.ConnectProcessor.dispatch(ConnectProcessor.java:259) [palo-fe.jar:?]
        at org.apache.doris.qe.ConnectProcessor.processOnce(ConnectProcessor.java:393) [palo-fe.jar:?]
        at org.apache.doris.qe.ConnectProcessor.loop(ConnectProcessor.java:403) [palo-fe.jar:?]
        at org.apache.doris.qe.ConnectScheduler$LoopHandler.run(ConnectScheduler.java:172) [palo-fe.jar:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_131]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_131]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_131]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_131]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]
2019-10-20 13:00:06,405 WARN 2172 [StmtExecutor.execute():294] execute Exception.
org.apache.doris.common.AnalysisException: Unexpected exception: null
        at org.apache.doris.qe.StmtExecutor.analyze(StmtExecutor.java:466) ~[palo-fe.jar:?]
        at org.apache.doris.qe.StmtExecutor.execute(StmtExecutor.java:213) [palo-fe.jar:?]
        at org.apache.doris.qe.ConnectProcessor.handleQuery(ConnectProcessor.java:168) [palo-fe.jar:?]
        at org.apache.doris.qe.ConnectProcessor.dispatch(ConnectProcessor.java:259) [palo-fe.jar:?]
        at org.apache.doris.qe.ConnectProcessor.processOnce(ConnectProcessor.java:393) [palo-fe.jar:?]
        at org.apache.doris.qe.ConnectProcessor.loop(ConnectProcessor.java:403) [palo-fe.jar:?]
        at org.apache.doris.qe.ConnectScheduler$LoopHandler.run(ConnectScheduler.java:172) [palo-fe.jar:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_131]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_131]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_131]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_131]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]
```

This is related to #2003

**Comment by EmmyMiao87** [comment]
#2021
