### ISSUE TITLE
BE Crash in our regression environment

### ISSUE THREAD

**Issue by imay** [apache/incubator-doris#2041]
Be crash in our regression environment today. The stack is below
```
(gdb) bt
#0  doris::faststring::append (this=this@entry=0x122f7350, src_v=0x10da38001, count=count@entry=1) at /home/palo-ci/CI/workspace/doris_daily_qacitool_compile/core/be/src/util/faststring.h:127
#1  0x00000000015c53da in doris::segment_v2::BitshufflePageBuilder<(doris::FieldType)1>::add (this=0x122f7328, vals=<optimized out>, count=0x7f9f0fbc7408) at /home/palo-ci/CI/workspace/doris_daily_qacitool_compile/core/be/src/olap/rowset/segment_v2/bitshuffle_page.h:100
#2  0x00000000015b4359 in doris::segment_v2::ColumnWriter::_append_data (this=this@entry=0xfca7200, ptr=ptr@entry=0x7f9f0fbc74c8, num_rows=num_rows@entry=1)
    at /home/palo-ci/CI/workspace/doris_daily_qacitool_compile/core/be/src/olap/rowset/segment_v2/column_writer.cpp:143
#3  0x00000000015b53e5 in doris::segment_v2::ColumnWriter::append_nullable (this=<optimized out>, is_null_bits=is_null_bits@entry=0x7f9f0fbc7570 "", data=<optimized out>, num_rows=num_rows@entry=1)
    at /home/palo-ci/CI/workspace/doris_daily_qacitool_compile/core/be/src/olap/rowset/segment_v2/column_writer.cpp:179
#4  0x000000000157fa5f in append<doris::RowCursorCell> (cell=<synthetic pointer>, this=<optimized out>) at /home/palo-ci/CI/workspace/doris_daily_qacitool_compile/core/be/src/olap/rowset/segment_v2/column_writer.h:72
#5  doris::segment_v2::SegmentWriter::append_row<doris::RowCursor> (this=0xed2c380, row=...) at /home/palo-ci/CI/workspace/doris_daily_qacitool_compile/core/be/src/olap/rowset/segment_v2/segment_writer.cpp:80
#6  0x0000000000f49c3a in doris::BetaRowsetWriter::_add_row<doris::RowCursor> (this=0x103949320, row=...) at /home/palo-ci/CI/workspace/doris_daily_qacitool_compile/core/be/src/olap/rowset/beta_rowset_writer.cpp:89
#7  0x0000000000ee28ce in doris::Merger::merge_rowsets (tablet=..., reader_type=<optimized out>, src_rowset_readers=..., dst_rowset_writer=dst_rowset_writer@entry=0x103949320, stats_output=stats_output@entry=0x7f9f0fbc84c0)
    at /home/palo-ci/CI/workspace/doris_daily_qacitool_compile/core/be/src/olap/merger.cpp:62
#8  0x0000000000ed092e in doris::Compaction::do_compaction (this=this@entry=0x7f9f0fbc8800) at /home/palo-ci/CI/workspace/doris_daily_qacitool_compile/core/be/src/olap/compaction.cpp:53
#9  0x0000000000ec87d4 in doris::BaseCompaction::compact (this=this@entry=0x7f9f0fbc8800) at /home/palo-ci/CI/workspace/doris_daily_qacitool_compile/core/be/src/olap/base_compaction.cpp:44
#10 0x0000000000e5c7d4 in doris::StorageEngine::perform_base_compaction (this=this@entry=0x5862580, data_dir=data_dir@entry=0x5906a00) at /home/palo-ci/CI/workspace/doris_daily_qacitool_compile/core/be/src/olap/storage_engine.cpp:556
#11 0x0000000000ef1e50 in doris::StorageEngine::_base_compaction_thread_callback (this=0x5862580, arg=arg@entry=0x0, data_dir=0x5906a00) at /home/palo-ci/CI/workspace/doris_daily_qacitool_compile/core/be/src/olap/olap_server.cpp:171
#12 0x0000000000ef1f11 in operator() (__closure=<optimized out>) at /home/palo-ci/CI/workspace/doris_daily_qacitool_compile/core/be/src/olap/olap_server.cpp:74
#13 __invoke_impl<void, doris::StorageEngine::_start_bg_worker()::<lambda()> > (__f=...) at /home/palo-ci/CI/workspace/doris_daily_qacitool_compile/doris-toolchain/gcc730/include/c++/7.3.0/bits/invoke.h:60
#14 __invoke<doris::StorageEngine::_start_bg_worker()::<lambda()> > (__fn=...) at /home/palo-ci/CI/workspace/doris_daily_qacitool_compile/doris-toolchain/gcc730/include/c++/7.3.0/bits/invoke.h:95
#15 _M_invoke<0> (this=<optimized out>) at /home/palo-ci/CI/workspace/doris_daily_qacitool_compile/doris-toolchain/gcc730/include/c++/7.3.0/thread:234
#16 operator() (this=<optimized out>) at /home/palo-ci/CI/workspace/doris_daily_qacitool_compile/doris-toolchain/gcc730/include/c++/7.3.0/thread:243
#17 std::thread::_State_impl<std::thread::_Invoker<std::tuple<doris::StorageEngine::_start_bg_worker()::<lambda()> > > >::_M_run(void) (this=<optimized out>) at /home/palo-ci/CI/workspace/doris_daily_qacitool_compile/doris-toolchain/gcc730/include/c++/7.3.0/thread:186
#18 0x0000000002d6601f in std::execute_native_thread_routine (__p=0x596fc40) at ../../../../../gcc-7.3.0/libstdc++-v3/src/c++11/thread.cc:83
#19 0x00007f9f21bae1c3 in start_thread () from /opt/compiler/gcc-4.8.2/lib64/libpthread.so.0
#20 0x00007f9f21eab12d in clone () from /opt/compiler/gcc-4.8.2/lib64/libc.so.6
```

There are two problems
1. we are not switch BETA rowset on, why it was going to generate beta rowset when doing base compaction
2. Why it crash when it generate beta rowset.

This should be introduced through #2020 

commit:
0f94b685abe772e9a6037cdec176774334b763f0

**Comment by kangpinghuang** [comment]
The first problem is fixed by #2042
