### ISSUE TITLE
mini load 导入数据失败

### ISSUE THREAD

**Issue by Super-Alan** [apache/incubator-doris#240]
> **执行命令** 
>> curl --location-trusted -u root:****** -T testData http://118.*.*.*:9030/api/user_bhv_data/user_tag_score_datail/_load?label=2

>**testData 数据**
  1 1 0 test 3 "2018-01-01 12:00:00"

> **fe 错误信息:**
>> 2018-10-08 19:44:12,171 WARN 6576 [MysqlChannel.fetchOnePacket():143] receive packet sequence id[32] want to get[1]
2018-10-08 19:44:12,171 WARN 6576 [ConnectScheduler$LoopHandler.run():172] connect processor exception because 
java.io.IOException: Bad packet sequence.
        at com.baidu.palo.mysql.MysqlChannel.fetchOnePacket(MysqlChannel.java:144) ~[palo-fe.jar:?]
        at com.baidu.palo.mysql.MysqlProto.negotiate(MysqlProto.java:136) ~[palo-fe.jar:?]
        at com.baidu.palo.qe.ConnectScheduler$LoopHandler.run(ConnectScheduler.java:156) [palo-fe.jar:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_181]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_181]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_181]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_181]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]
2018-10-08 19:48:49,587 WARN 6577 [MysqlChannel.fetchOnePacket():143] receive packet sequence id[32] want to get[1]
2018-10-08 19:48:49,587 WARN 6577 [ConnectScheduler$LoopHandler.run():172] connect processor exception because 
java.io.IOException: Bad packet sequence.
        at com.baidu.palo.mysql.MysqlChannel.fetchOnePacket(MysqlChannel.java:144) ~[palo-fe.jar:?]
        at com.baidu.palo.mysql.MysqlProto.negotiate(MysqlProto.java:136) ~[palo-fe.jar:?]
        at com.baidu.palo.qe.ConnectScheduler$LoopHandler.run(ConnectScheduler.java:156) [palo-fe.jar:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_181]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_181]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_181]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_181]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]

请问上述问题 一般该如何解决

**Comment by MrGreen1024** [comment]
请问问题解决了吗，是什么原因呀
