### ISSUE TITLE
The BE accidental core during query

### ISSUE THREAD

**Issue by EmmyMiao87** [apache/incubator-doris#2504]
**Describe the bug**
The BE accidental core during query

**To Reproduce**
CREATE TABLE `left_table` (
  `k1` tinyint(4) NOT NULL COMMENT "",
  `k2` tinyint(4) NOT NULL COMMENT ""
) ENGINE=OLAP
AGGREGATE KEY(`k1`, `k2`)
COMMENT "OLAP"
DISTRIBUTED BY HASH(`k1`) BUCKETS 5
PROPERTIES (
"storage_type" = "COLUMN"
);
CREATE TABLE `test` (
  `k1` tinyint(4) NOT NULL COMMENT "",
  `k2` smallint(6) NOT NULL COMMENT "",
  `k3` int(11) NOT NULL COMMENT "",
  `k4` bigint(20) NOT NULL COMMENT "",
  `k5` decimal(9, 3) NOT NULL COMMENT "",
  `k6` char(5) NOT NULL COMMENT "",
  `k10` date NOT NULL COMMENT "",
  `k11` datetime NOT NULL COMMENT "",
  `k7` varchar(20) NOT NULL COMMENT "",
  `k8` double MAX NOT NULL COMMENT "",
  `k9` float SUM NOT NULL COMMENT ""
) ENGINE=OLAP
AGGREGATE KEY(`k1`, `k2`, `k3`, `k4`, `k5`, `k6`, `k10`, `k11`, `k7`)
COMMENT "OLAP"
DISTRIBUTED BY HASH(`k1`) BUCKETS 5
PROPERTIES (
"storage_type" = "COLUMN"
);
mysql> select * From test;
+------+------+------+------+------+------+------------+---------------------+------+------+------+
| k1   | k2   | k3   | k4   | k5   | k6   | k10        | k11                 | k7   | k8   | k9   |
+------+------+------+------+------+------+------------+---------------------+------+------+------+
|    1 |    2 |    3 |    4 |    5 | 6    | 2019-10-10 | 2019-10-10 00:00:00 | 7    |    8 |  117 |
+------+------+------+------+------+------+------------+---------------------+------+------+------+
mysql> select * From left_table;
+------+------+
| k1   | k2   |
+------+------+
|    1 |    3 |
|    1 |   13 |
+------+------+
select * from left_table where k1=(select k1 from test);
query hang and be core

The core info like that
```    
#0 0x2abdce6 in doris::RowBatch::capacity() const /home/disk0/miaoling/workspace/baidu/bdg/doris/core/be/src/runtime/row_batch.h:385
    #1 0x2abdce6 in doris::ExchangeNode::get_next(doris::RuntimeState*, doris::RowBatch*, bool*) /home/disk0/miaoling/workspace/baidu/bdg/doris/core/be/src/exec/exchange_node.cpp:156
    #2 0x2e7b4a1 in doris::AssertNumRowsNode::get_next(doris::RuntimeState*, doris::RowBatch*, bool*) /home/disk0/miaoling/workspace/baidu/bdg/doris/core/be/src/exec/assert_num_rows_node.cpp:55
    #3 0x1c3c0d3 in doris::PlanFragmentExecutor::get_next_internal(doris::RowBatch**) /home/disk0/miaoling/workspace/baidu/bdg/doris/core/be/src/runtime/plan_fragment_executor.cpp:495
```

**Expected behavior**
mysql> select * from left_table where k1=(select k1 from test);
+------+------+
| k1   | k2   |
+------+------+
|    1 |    3 |
|    1 |   13 |
+------+------+
2 rows in set (0.02 sec)

**Comment by EmmyMiao87** [comment]
The core log is the same issue.
```
#0  doris::MemPool::acquire_data (this=0xab9b200, src=0x1448a30 <doris::TOlapTablePartitionParam::printTo(std::ostream&) const>, 
    keep_current=keep_current@entry=false) at /home/work/teamcity/workspace/doris_daily_compile/core/be/src/runtime/mem_pool.cpp:156
#1  0x00000000011fbcd0 in doris::RowBatch::transfer_resource_ownership (this=0x32119f0 <vtable for doris::TSlotDescriptor+16>, dest=dest@entry=0x1a6c8840)
    at /home/work/teamcity/workspace/doris_daily_compile/core/be/src/runtime/row_batch.cpp:519
#2  0x00000000015ee3ca in doris::ExchangeNode::get_next (this=0x36790700, state=0x1c486300, output_batch=0x1a6c8840, eos=0x111b29e9)
    at /home/work/teamcity/workspace/doris_daily_compile/core/be/src/exec/exchange_node.cpp:195
#3  0x00000000017028aa in doris::AssertNumRowsNode::get_next (this=0x31af2b40, state=0x1c486300, output_batch=0x1a6c8840, eos=0x111b29e9)
    at /home/work/teamcity/workspace/doris_daily_compile/core/be/src/exec/assert_num_rows_node.cpp:55
```
