### ISSUE TITLE
java.lang.ClassCastException: org.apache.doris.analysis.CreateIndexClause cannot be cast to org.apache.doris.analysis.AlterTableClause

### ISSUE THREAD

**Issue by songenjie** [apache/incubator-doris#2664]
2020-01-06 15:13:32,200 WARN 172 [StmtExecutor.handleDdlStmt():847] DDL statement(ALTER TABLE bitmap_test  ADD INDEX modified (modified) USING BITMAP COMMENT 'modified') process failed.
java.lang.ClassCastException: org.apache.doris.analysis.CreateIndexClause cannot be cast to org.apache.doris.analysis.AlterTableClause
	at org.apache.doris.alter.Alter.processAlterTable(Alter.java:178) ~[palo-fe.jar:?]
	at org.apache.doris.catalog.Catalog.alterTable(Catalog.java:4779) ~[palo-fe.jar:?]
	at org.apache.doris.qe.DdlExecutor.execute(DdlExecutor.java:104) ~[palo-fe.jar:?]
	at org.apache.doris.qe.StmtExecutor.handleDdlStmt(StmtExecutor.java:840) [palo-fe.jar:?]
	at org.apache.doris.qe.StmtExecutor.execute(StmtExecutor.java:274) [palo-fe.jar:?]
	at org.apache.doris.qe.ConnectProcessor.handleQuery(ConnectProcessor.java:169) [palo-fe.jar:?]
	at org.apache.doris.qe.ConnectProcessor.dispatch(ConnectProcessor.java:260) [palo-fe.jar:?]
	at org.apache.doris.qe.ConnectProcessor.processOnce(ConnectProcessor.java:420) [palo-fe.jar:?]
	at org.apache.doris.qe.ConnectProcessor.loop(ConnectProcessor.java:430) [palo-fe.jar:?]
	at org.apache.doris.qe.ConnectScheduler$LoopHandler.run(ConnectScheduler.java:172) [palo-fe.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_121]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_121]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_121]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_121]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]

**Comment by Wsyzxxn** [comment]
https://github.com/apache/incubator-doris/pull/2667/files
