### ISSUE TITLE
fail to show processlist 

### ISSUE THREAD

**Issue by imay** [apache/incubator-doris#2677]
**Describe the bug**
After I apply this patch #2603 , there is an error when I executed `show processlist` with  `mysql_service_nio_enabled` in fe.conf set true

The call stack is following

```
2020-01-06 19:42:32,646 WARN 132 [StmtExecutor.execute():298] execute Exception
java.lang.NullPointerException: null
        at org.apache.doris.qe.ConnectContext$ThreadInfo.toRow(ConnectContext.java:379) ~[palo-fe.jar:?]
        at org.apache.doris.qe.ShowExecutor.handleShowProcesslist(ShowExecutor.java:270) ~[palo-fe.jar:?]
        at org.apache.doris.qe.ShowExecutor.execute(ShowExecutor.java:181) ~[palo-fe.jar:?]
        at org.apache.doris.qe.StmtExecutor.handleShow(StmtExecutor.java:809) ~[palo-fe.jar:?]
        at org.apache.doris.qe.StmtExecutor.execute(StmtExecutor.java:276) ~[palo-fe.jar:?]
        at org.apache.doris.qe.ConnectProcessor.handleQuery(ConnectProcessor.java:169) ~[palo-fe.jar:?]
        at org.apache.doris.qe.ConnectProcessor.dispatch(ConnectProcessor.java:260) ~[palo-fe.jar:?]
        at org.apache.doris.qe.ConnectProcessor.processOnce(ConnectProcessor.java:420) ~[palo-fe.jar:?]
        at org.apache.doris.mysql.nio.ReadListener.lambda$handleEvent$0(ReadListener.java:50) ~[palo-fe.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_131]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_131]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]
```

**Comment by infearOnTheWay** [comment]
Thanks for finding the problem @imay . 
After check the code, I found the field `mysqlChannel` is not initialized in `NConnectContext` which inherit from `ConnectContext`, then the field is used in `ThreadInfo`. I would check relative logic about this field and fix it.
