### ISSUE TITLE
Create hdfs broker external table, query failed 

### ISSUE THREAD

**Issue by zhangy5** [apache/incubator-doris#2742]
**Describe the bug**
Create hdfs broker external table, SELECT * failed: Unexpected exception: null
fe log:
2020-01-13 16:27:07,696 WARN 188 [StmtExecutor.analyze():465] Analyze failed because
java.lang.NullPointerException: null
        at org.apache.doris.load.Load.initColumns(Load.java:880) ~[palo-fe.jar:?]
        at org.apache.doris.planner.BrokerScanNode.initColumns(BrokerScanNode.java:230) ~[palo-fe.jar:?]
        at org.apache.doris.planner.BrokerScanNode.initParams(BrokerScanNode.java:212) ~[palo-fe.jar:?]
        at org.apache.doris.planner.BrokerScanNode.init(BrokerScanNode.java:166) ~[palo-fe.jar:?]
        at org.apache.doris.planner.SingleNodePlanner.createScanNode(SingleNodePlanner.java:1284) ~[palo-fe.jar:?]
        at org.apache.doris.planner.SingleNodePlanner.createTableRefNode(SingleNodePlanner.java:1429) ~[palo-fe.jar:?]
        at org.apache.doris.planner.SingleNodePlanner.createSelectPlan(SingleNodePlanner.java:669) ~[palo-fe.jar:?]
        at org.apache.doris.planner.SingleNodePlanner.createQueryPlan(SingleNodePlanner.java:215) ~[palo-fe.jar:?]
        at org.apache.doris.planner.SingleNodePlanner.createSingleNodePlan(SingleNodePlanner.java:146) ~[palo-fe.jar:?]
        at org.apache.doris.planner.Planner.createPlanFragments(Planner.java:146) ~[palo-fe.jar:?]
        at org.apache.doris.planner.Planner.plan(Planner.java:78) ~[palo-fe.jar:?]
        at org.apache.doris.qe.StmtExecutor.analyze(StmtExecutor.java:453) ~[palo-fe.jar:?]
        at org.apache.doris.qe.StmtExecutor.execute(StmtExecutor.java:213) ~[palo-fe.jar:?]
        at org.apache.doris.qe.ConnectProcessor.handleQuery(ConnectProcessor.java:169) ~[palo-fe.jar:?]
        at org.apache.doris.qe.ConnectProcessor.dispatch(ConnectProcessor.java:260) ~[palo-fe.jar:?]
        at org.apache.doris.qe.ConnectProcessor.processOnce(ConnectProcessor.java:420) ~[palo-fe.jar:?]
        at org.apache.doris.mysql.nio.ReadListener.lambda$handleEvent$0(ReadListener.java:50) ~[palo-fe.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_131]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_131]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]
2020-01-13 16:27:07,697 WARN 188 [StmtExecutor.execute():294] execute Exception. Unexpected exception: null

**To Reproduce**
1. CREATE DATABASE test_sys_pull_load_external_test_hdfs_external_table_csv_db

2. CREATE EXTERNAL TABLE test_sys_pull_load_external_test_hdfs_external_table_csv_db.test_sys_pull_load_external_test_hdfs_external_table_csv_tb ( tinyint_key TINYINT NOT NULL, smallint_key SMALLINT NOT NULL, int_key INT NOT NULL, bigint_key BIGINT NOT NULL, largeint_key LARGEINT NOT NULL, char_key CHAR(50) NOT NULL, varchar_key VARCHAR(65533) NOT NULL, decimal_key DECIMAL(27, 9) NOT NULL, date_key DATE NOT NULL, datetime_key DATETIME NOT NULL, tinyint_value_max TINYINT NOT NULL, smallint_value_min SMALLINT NOT NULL, int_value_sum INT NOT NULL, bigint_value_sum BIGINT NOT NULL, largeint_value_sum LARGEINT NOT NULL, largeint_value_replace LARGEINT NOT NULL, char_value_replace CHAR(50) NOT NULL, varchar_value_replace VARCHAR(65533) NOT NULL, decimal_value_replace DECIMAL(27, 9) NOT NULL, date_value_replace DATE NOT NULL, datetime_value_replace DATETIME NOT NULL, float_value_sum FLOAT NOT NULL, double_value_sum DOUBLE NOT NULL ) ENGINE=broker PROPERTIES ( "broker_name" = "hdfs",  "path" = "hdfs://host:port/user/palo/test/data/sys/pull_load/pull_load_data",  "column_separator" = "\t",  "format" = "csv") BROKER PROPERTIES ("username"="xxx", "password"="xxx")

3. SELECT * FROM test_sys_pull_load_external_test_hdfs_external_table_gz_db.test_sys_pull_load_external_test_hdfs_external_table_gz_tb

**Screenshots**
![image](https://user-images.githubusercontent.com/10826066/72241779-b152c100-3622-11ea-893a-b21ed02ce165.png)

**Comment by morningman** [comment]
2020-01-14 09:18:44,187 WARN 669 [StmtExecutor.analyze():465] Analyze failed because
java.lang.NullPointerException: null
        at org.apache.doris.load.Load.initColumns(Load.java:880) ~[palo-fe.jar:?]
        at org.apache.doris.planner.BrokerScanNode.initColumns(BrokerScanNode.java:230) ~[palo-fe.jar:?]
        at org.apache.doris.planner.BrokerScanNode.initParams(BrokerScanNode.java:212) ~[palo-fe.jar:?]
        at org.apache.doris.planner.BrokerScanNode.init(BrokerScanNode.java:166) ~[palo-fe.jar:?]
        at org.apache.doris.planner.SingleNodePlanner.createScanNode(SingleNodePlanner.java:1284) ~[palo-fe.jar:?]
        at org.apache.doris.planner.SingleNodePlanner.createTableRefNode(SingleNodePlanner.java:1429) ~[palo-fe.jar:?]
        at org.apache.doris.planner.SingleNodePlanner.createSelectPlan(SingleNodePlanner.java:669) ~[palo-fe.jar:?]
        at org.apache.doris.planner.SingleNodePlanner.createQueryPlan(SingleNodePlanner.java:215) ~[palo-fe.jar:?]
        at org.apache.doris.planner.SingleNodePlanner.createSingleNodePlan(SingleNodePlanner.java:146) ~[palo-fe.jar:?]
        at org.apache.doris.planner.Planner.createPlanFragments(Planner.java:146) ~[palo-fe.jar:?]
        at org.apache.doris.planner.Planner.plan(Planner.java:78) ~[palo-fe.jar:?]
        at org.apache.doris.qe.StmtExecutor.analyze(StmtExecutor.java:453) [palo-fe.jar:?]
        at org.apache.doris.qe.StmtExecutor.execute(StmtExecutor.java:213) [palo-fe.jar:?]
        at org.apache.doris.qe.ConnectProcessor.handleQuery(ConnectProcessor.java:169) [palo-fe.jar:?]
        at org.apache.doris.qe.ConnectProcessor.dispatch(ConnectProcessor.java:260) [palo-fe.jar:?]
        at org.apache.doris.qe.ConnectProcessor.processOnce(ConnectProcessor.java:420) [palo-fe.jar:?]
        at org.apache.doris.qe.ConnectProcessor.loop(ConnectProcessor.java:430) [palo-fe.jar:?]
        at org.apache.doris.qe.ConnectScheduler$LoopHandler.run(ConnectScheduler.java:177) [palo-fe.jar:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_131]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_131]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_131]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_131]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]
