### ISSUE TITLE
doris on es report 500 Internal Privoxy Error

### ISSUE THREAD

**Issue by hexian55** [apache/incubator-doris#2916]
**Describe the bug**

test doris on es, create es table:
CREATE EXTERNAL TABLE `doris_table_test`(
`id` int,
`name` varchar,
`info` varchar,
`age` int
) ENGINE=ELASTICSEARCH
PROPERTIES(
"hosts"="http://xxx:9201",
"index"="doris_table_test",
"type"="_doc"
);

select * from doris_table_test  

doris version:0.11
es version:7.4.2/6.8.6

Description: from the Doris log, you can see that after the creation of the ES table, Doris can connect to the ES cluster to query the cluster information

doris error log 
2020-02-13 17:47:17,589 WARN 196 [Coordinator.updateFragmentExecStatus():1171] one instance report fail, query_id=a7e3e63ba43b489b-9df29d7c7a45226f instance_id=a7e3e63ba43b489b-9df29d7c7a452270
2020-02-13 17:47:17,589 WARN 196 [Coordinator.updateStatus():599] one instance report fail throw updateStatus(), need cancel. job id: -1, query id: a7e3e63ba43b489b-9df29d7c7a45226f, instance id: a7e3e63ba43b489b-9df29d7c7a452270
2020-02-13 17:47:17,590 WARN 994 [Coordinator.getNext():617] get next fail, need cancel. query id: a7e3e63ba43b489b-9df29d7c7a45226f
2020-02-13 17:47:17,590 WARN 994 [Coordinator.getNext():637] query failed: Failed to connect to ES server, errmsg is: The requested URL returned error: 500 Internal Privoxy Error
2020-02-13 17:47:17,590 WARN 790 [Coordinator.updateFragmentExecStatus():1171] one instance report fail, query_id=a7e3e63ba43b489b-9df29d7c7a45226f instance_id=a7e3e63ba43b489b-9df29d7c7a452271
2020-02-13 17:47:17,591 WARN 994 [StmtExecutor.execute():298] execute Exception
org.apache.doris.common.UserException: Failed to connect to ES server, errmsg is: The requested URL returned error: 500 Internal Privoxy Error
	at org.apache.doris.qe.Coordinator.getNext(Coordinator.java:644) ~[palo-fe.jar:?]
	at org.apache.doris.qe.StmtExecutor.handleQueryStmt(StmtExecutor.java:559) ~[palo-fe.jar:?]
	at org.apache.doris.qe.StmtExecutor.execute(StmtExecutor.java:226) [palo-fe.jar:?]
	at org.apache.doris.qe.ConnectProcessor.handleQuery(ConnectProcessor.java:168) [palo-fe.jar:?]
	at org.apache.doris.qe.ConnectProcessor.dispatch(ConnectProcessor.java:259) [palo-fe.jar:?]
	at org.apache.doris.qe.ConnectProcessor.processOnce(ConnectProcessor.java:393) [palo-fe.jar:?]
	at org.apache.doris.qe.ConnectProcessor.loop(ConnectProcessor.java:403) [palo-fe.jar:?]
	at org.apache.doris.qe.ConnectScheduler$LoopHandler.run(ConnectScheduler.java:172) [palo-fe.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_242]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_242]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_242]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_242]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242]

**Comment by wuyunfeng** [comment]
@hexian55   hi,  whether  port `9201` is http port？

**Comment by hexian55** [comment]
Of course, if the address is wrong or the index does not exist, the error message is not like this

**Comment by wuyunfeng** [comment]
Can you provide the `sql` you executed?  This Internal `Privoxy` Error  is so confused.
Another way, can you see the log of your ES  cluster (node which contains the shard of the index) when you send `sql` for this ES external table?  by the way, the `hosts` you provided is a LB(load balance)?

**Comment by hexian55** [comment]
1.executed any sql,has same as the error log.
3.es host is es node domain,not LB  proxy or vpn


if i create new table, can see fe node logs:
2020-02-18 11:06:22,877 INFO 4556 [EsStateStore.registerTable():77] register a new table [Table [id=11040, name=doris_table_test4, type=ELASTICSEARCH]] to sync list
2020-02-18 11:06:22,877 INFO 4556 [Catalog.createEsTable():3642] successfully create tabledoris_table_test4 with id 11040

next to executed select sql,  es cluster not has any error or warn log.

**Comment by wuyunfeng** [comment]
> next to executed select sql, es cluster not has any error or warn log.
Maybe Elasticsearch cluster does not receive any request because of networking issue.

Could you provide the `tcp packet` send to 9201 port which can obtained from `tcpdump -i {network card} src port 9201 or dst port 9201 -w doris_on_es.pcap`?

**Comment by hexian55** [comment]
I'm sure it's not the ES cluster configuration and network problems.
please see my issue Description,if i set es Index does not exist,the error msg like this:

2020-02-18 14:58:43,266 WARN 4691 [StmtExecutor.analyze():465] Analyze failed because
java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at java.util.ArrayList.rangeCheck(ArrayList.java:657) ~[?:1.8.0_242]
	at java.util.ArrayList.get(ArrayList.java:433) ~[?:1.8.0_242]
	at org.apache.doris.planner.EsScanNode.getShardLocations(EsScanNode.java:220) ~[palo-fe.jar:?]
	at org.apache.doris.planner.EsScanNode.finalize(EsScanNode.java:102) ~[palo-fe.jar:?]
	at org.apache.doris.planner.Planner.createPlanFragments(Planner.java:162) ~[palo-fe.jar:?]
	at org.apache.doris.planner.Planner.plan(Planner.java:78) ~[palo-fe.jar:?]
	at org.apache.doris.qe.StmtExecutor.analyze(StmtExecutor.java:453) [palo-fe.jar:?]
	at org.apache.doris.qe.StmtExecutor.execute(StmtExecutor.java:213) [palo-fe.jar:?]
	at org.apache.doris.qe.ConnectProcessor.handleQuery(ConnectProcessor.java:168) [palo-fe.jar:?]
	at org.apache.doris.qe.ConnectProcessor.dispatch(ConnectProcessor.java:259) [palo-fe.jar:?]
	at org.apache.doris.qe.ConnectProcessor.processOnce(ConnectProcessor.java:393) [palo-fe.jar:?]
	at org.apache.doris.qe.ConnectProcessor.loop(ConnectProcessor.java:403) [palo-fe.jar:?]
	at org.apache.doris.qe.ConnectScheduler$LoopHandler.run(ConnectScheduler.java:172) [palo-fe.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_242]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_242]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_242]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_242]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242]

**Comment by hexian55** [comment]
@imay   @morningman   Please help me

**Comment by imay** [comment]
> @imay @morningman Please help me

Could we talk with weixin? My id is ApacheZhaoc

**Comment by wuyunfeng** [comment]
@hexian55  你加下 imay的微信，我们拉个讨论组，最近太忙把这事给忘了

**Comment by hexian55** [comment]
ok
