### ISSUE TITLE
hdfs load error

### ISSUE THREAD

**Issue by chaiyuan2046** [apache/incubator-doris#3035]
2020-03-04 18:56:52,407 WARN 564 [LoadJob.unprotectedExecuteCancel():528] LOAD_JOB=10157, transaction_id={11}, error_msg={Failed to execute load with error No source file in this table(user_all_user_doris).}
2020-03-04 19:08:01,485 WARN 565 [BrokerLoadJob.onPendingTaskFinished():325] LOAD_JOB=10160, database_id={10003}, error_msg={Failed to divide job into loading task.}
org.apache.doris.common.UserException: No source file in this table(user_all_user_doris).
        at org.apache.doris.planner.BrokerScanNode.getFileStatusAndCalcInstance(BrokerScanNode.java:377) ~[palo-fe.jar:?]
        at org.apache.doris.planner.BrokerScanNode.init(BrokerScanNode.java:158) ~[palo-fe.jar:?]
        at org.apache.doris.load.loadv2.LoadingTaskPlanner.plan(LoadingTaskPlanner.java:117) ~[palo-fe.jar:?]
        at org.apache.doris.load.loadv2.LoadLoadingTask.init(LoadLoadingTask.java:85) ~[palo-fe.jar:?]
        at org.apache.doris.load.loadv2.BrokerLoadJob.createLoadingTask(BrokerLoadJob.java:361) ~[palo-fe.jar:?]
        at org.apache.doris.load.loadv2.BrokerLoadJob.onPendingTaskFinished(BrokerLoadJob.java:323) [palo-fe.jar:?]
        at org.apache.doris.load.loadv2.BrokerLoadJob.onTaskFinished(BrokerLoadJob.java:214) [palo-fe.jar:?]
        at org.apache.doris.load.loadv2.LoadTask.exec(LoadTask.java:51) [palo-fe.jar:?]
        at org.apache.doris.task.MasterTask.run(MasterTask.java:31) [palo-fe.jar:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_144]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_144]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_144]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_144]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_144]

**Comment by imay** [comment]
@chaiyuan2046 Can you provide more information?
