### ISSUE TITLE
[Bug] BE crash

### ISSUE THREAD

**Issue by morningman** [apache/incubator-doris#4270]
**Describe the bug**
BE will crash after merging #4237

**Comment by morningman** [comment]
```
#0  0x0000000001064335 in doris::PlanFragmentExecutor::open_internal (this=this@entry=0x16266330) at /home/work/teamcity/agent/work/4304a7ff82e9a41d/core/be/src/runtime/plan_fragment_executor.cpp:279
#1  0x0000000001064a8c in doris::PlanFragmentExecutor::open (this=this@entry=0x16266330) at /home/work/teamcity/agent/work/4304a7ff82e9a41d/core/be/src/runtime/plan_fragment_executor.cpp:244
#2  0x0000000000ff2bab in doris::FragmentExecState::execute (this=0x162662c0) at /home/work/teamcity/agent/work/4304a7ff82e9a41d/core/be/src/runtime/fragment_mgr.cpp:217
#3  0x0000000000ff5166 in doris::FragmentMgr::exec_actual(std::shared_ptr<doris::FragmentExecState>, std::function<void (doris::PlanFragmentExecutor*)>) (this=0x4bbe5a0, exec_state=..., cb=...)
    at /home/work/teamcity/agent/work/4304a7ff82e9a41d/core/be/src/runtime/fragment_mgr.cpp:417
#4  0x0000000000ffa1fc in __invoke_impl<void, void (doris::FragmentMgr::*&)(std::shared_ptr<doris::FragmentExecState>, std::function<void(doris::PlanFragmentExecutor*)>), doris::FragmentMgr*&, std::shared_ptr<doris::FragmentExecState>&, std::function<void(doris::PlanFragmentExecutor*)>&> (__t=@0x525ee50: 0x4bbe5a0, __f=
    @0x525ee10: (void (doris::FragmentMgr::*)(doris::FragmentMgr * const, std::shared_ptr<doris::FragmentExecState>, std::function<void(doris::PlanFragmentExecutor*)>)) 0xff5140 <doris::FragmentMgr::exec_actual(std::shared_ptr<doris::FragmentExecState>, std::function<void (doris::PlanFragmentExecutor*)>)>) at /home/work/teamcity/agent/work/4304a7ff82e9a41d/doris-toolchain/gcc730/include/c++/7.3.0/bits/invoke.h:73
#5  __invoke<void (doris::FragmentMgr::*&)(std::shared_ptr<doris::FragmentExecState>, std::function<void(doris::PlanFragmentExecutor*)>), doris::FragmentMgr*&, std::shared_ptr<doris::FragmentExecState>&, std::function<void(doris::PlanFragmentExecutor*)>&> (__fn=
    @0x525ee10: (void (doris::FragmentMgr::*)(doris::FragmentMgr * const, std::shared_ptr<doris::FragmentExecState>, std::function<void(doris::PlanFragmentExecutor*)>)) 0xff5140 <doris::FragmentMgr::exec_actual(std::shared_ptr<doris::FragmentExecState>, std::function<void (doris::PlanFragmentExecutor*)>)>) at /home/work/teamcity/agent/work/4304a7ff82e9a41d/doris-toolchain/gcc730/include/c++/7.3.0/bits/invoke.h:95
#6  __call<void, 0, 1, 2> (__args=..., this=0x525ee10) at /home/work/teamcity/agent/work/4304a7ff82e9a41d/doris-toolchain/gcc730/include/c++/7.3.0/functional:632
#7  operator()<> (this=0x525ee10) at /home/work/teamcity/agent/work/4304a7ff82e9a41d/doris-toolchain/gcc730/include/c++/7.3.0/functional:718
#8  std::_Function_handler<void (), std::_Bind_result<void, void (doris::FragmentMgr::*(doris::FragmentMgr*, std::shared_ptr<doris::FragmentExecState>, std::function<void (doris::PlanFragmentExecutor*)>))(std::shared_ptr<doris::FragmentExecState>, std::function<void (doris::PlanFragmentExecutor*)>)> >::_M_invoke(std::_Any_data const&) (__functor=...) at /home/work/teamcity/agent/work/4304a7ff82e9a41d/doris-toolchain/gcc730/include/c++/7.3.0/bits/std_function.h:316
#9  0x000000000116c742 in operator() (this=0x9b83658) at /home/work/teamcity/agent/work/4304a7ff82e9a41d/doris-toolchain/gcc730/include/c++/7.3.0/bits/std_function.h:706
#10 run (this=0x9b83650) at /home/work/teamcity/agent/work/4304a7ff82e9a41d/core/be/src/util/threadpool.cpp:42
#11 doris::ThreadPool::dispatch_thread (this=0x52672c0) at /home/work/teamcity/agent/work/4304a7ff82e9a41d/core/be/src/util/threadpool.cpp:551
#12 0x000000000117e5b8 in operator() (this=0x51de3d8) at /home/work/teamcity/agent/work/4304a7ff82e9a41d/doris-toolchain/gcc730/include/c++/7.3.0/bits/std_function.h:706
#13 doris::Thread::supervise_thread (arg=0x51de3c0) at /home/work/teamcity/agent/work/4304a7ff82e9a41d/core/be/src/util/thread.cpp:385
#14 0x00007ff3eca3f1c3 in start_thread () from /opt/compiler/gcc-4.8.2/lib64/libpthread.so.0
#15 0x00007ff3ecd3c12d in clone () from /opt/compiler/gcc-4.8.2/lib64/libc.so.6
```

**Comment by morningman** [comment]
```
#0  0x0000000001067225 in doris::PlanFragmentExecutor::report_profile (this=0x120c2e30) at /home/work/teamcity/agent/work/4304a7ff82e9a41d/core/be/src/runtime/plan_fragment_executor.cpp:386
#1  0x0000000001ab183d in thread_proxy ()
#2  0x00007f7da407e1c3 in start_thread () from /opt/compiler/gcc-4.8.2/lib64/libpthread.so.0
#3  0x00007f7da437b12d in clone () from /opt/compiler/gcc-4.8.2/lib64/libc.so.6
```
