### ISSUE TITLE
[FE] fe out of service when some be dead

### ISSUE THREAD

**Issue by francisoliverlee** [apache/incubator-doris#4414]
**Describe the bug**
fe not alive on fe UI console when some be dead

**Expected behavior**
FEs run OK, be dead

**Screenshots**
FE log

```java
2020-08-21 02:05:41,172 WARN 35 [TabletStatMgr.runAfterCatalogReady():69] task exec error. backend[10007]
org.apache.thrift.transport.TTransportException: java.net.ConnectException: 拒绝连接 (Connection refused)
	at org.apache.thrift.transport.TSocket.open(TSocket.java:226) ~[libthrift-0.9.3.jar:0.9.3]
	at org.apache.doris.common.GenericPool$ThriftClientFactory.create(GenericPool.java:128) ~[palo-fe.jar:?]
	at org.apache.doris.common.GenericPool$ThriftClientFactory.create(GenericPool.java:113) ~[palo-fe.jar:?]
	at org.apache.commons.pool2.BaseKeyedPooledObjectFactory.makeObject(BaseKeyedPooledObjectFactory.java:62) ~[commons-pool2-2.2.jar:2.2]
	at org.apache.commons.pool2.impl.GenericKeyedObjectPool.create(GenericKeyedObjectPool.java:1012) ~[commons-pool2-2.2.jar:2.2]
	at org.apache.commons.pool2.impl.GenericKeyedObjectPool.borrowObject(GenericKeyedObjectPool.java:356) ~[commons-pool2-2.2.jar:2.2]
	at org.apache.commons.pool2.impl.GenericKeyedObjectPool.borrowObject(GenericKeyedObjectPool.java:277) ~[commons-pool2-2.2.jar:2.2]
	at org.apache.doris.common.GenericPool.borrowObject(GenericPool.java:85) ~[palo-fe.jar:?]
	at org.apache.doris.catalog.TabletStatMgr.runAfterCatalogReady(TabletStatMgr.java:61) [palo-fe.jar:?]
	at org.apache.doris.common.util.MasterDaemon.runOneCycle(MasterDaemon.java:58) [palo-fe.jar:?]
	at org.apache.doris.common.util.Daemon.run(Daemon.java:116) [palo-fe.jar:?]
Caused by: java.net.ConnectException: 拒绝连接 (Connection refused)
	at java.net.PlainSocketImpl.socketConnect(Native Method) ~[?:1.8.0_251]
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350) ~[?:1.8.0_251]
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206) ~[?:1.8.0_251]
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188) ~[?:1.8.0_251]
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392) ~[?:1.8.0_251]
	at java.net.Socket.connect(Socket.java:606) ~[?:1.8.0_251]
	at org.apache.thrift.transport.TSocket.open(TSocket.java:221) ~[libthrift-0.9.3.jar:0.9.3]
	... 10 more

2020-08-21 02:05:40,284 WARN 73 [BDBEnvironment.openDatabase():255] get exception when try to close previously opened bdb database. ignore it
com.sleepycat.je.rep.DatabasePreemptedException: (JE 7.3.7) (JE 7.3.7) Database 4538523 has been forcibly closed in order to apply a replicated remove operation.  This Database and all associated Cursors must be closed.  All associated Transactions must be aborted.
	at com.sleepycat.je.rep.DatabasePreemptedException.wrapSelf(DatabasePreemptedException.java:113) ~[je-7.3.7.jar:7.3.7]
	at com.sleepycat.je.Database.checkOpen(Database.java:2274) ~[je-7.3.7.jar:7.3.7]
	at com.sleepycat.je.Database.getDatabaseName(Database.java:2046) ~[je-7.3.7.jar:7.3.7]
	at org.apache.doris.journal.bdbje.BDBEnvironment.openDatabase(BDBEnvironment.java:231) [palo-fe.jar:?]
	at org.apache.doris.journal.bdbje.BDBJEJournal.getMaxJournalId(BDBJEJournal.java:269) [palo-fe.jar:?]
	at org.apache.doris.persist.EditLog.getMaxJournalId(EditLog.java:94) [palo-fe.jar:?]
	at org.apache.doris.catalog.Catalog.getMaxJournalId(Catalog.java:4661) [palo-fe.jar:?]
	at org.apache.doris.catalog.Catalog.replayJournal(Catalog.java:2385) [palo-fe.jar:?]
	at org.apache.doris.catalog.Catalog$3.runOneCycle(Catalog.java:2190) [palo-fe.jar:?]
	at org.apache.doris.common.util.Daemon.run(Daemon.java:116) [palo-fe.jar:?]
Caused by: com.sleepycat.je.rep.DatabasePreemptedException: (JE 7.3.7) Database 4538523 has been forcibly closed in order to apply a replicated remove operation.  This Database and all associated Cursors must be closed.  All associated Transactions must be aborted.
	at com.sleepycat.je.rep.impl.RepImpl.createDatabasePreemptedException(RepImpl.java:2008) ~[je-7.3.7.jar:7.3.7]
	at com.sleepycat.je.rep.impl.RepImpl.createDatabasePreemptedException(RepImpl.java:143) ~[je-7.3.7.jar:7.3.7]
	at com.sleepycat.je.Database.setPreempted(Database.java:469) ~[je-7.3.7.jar:7.3.7]
	at com.sleepycat.je.DbInternal.setPreempted(DbInternal.java:58) ~[je-7.3.7.jar:7.3.7]
	at com.sleepycat.je.dbi.DbTree.lockNameLN(DbTree.java:972) ~[je-7.3.7.jar:7.3.7]
	at com.sleepycat.je.dbi.DbTree.doRemoveDb(DbTree.java:1172) ~[je-7.3.7.jar:7.3.7]
	at com.sleepycat.je.dbi.DbTree.removeReplicaDb(DbTree.java:1239) ~[je-7.3.7.jar:7.3.7]
	at com.sleepycat.je.rep.impl.node.Replay.applyNameLN(Replay.java:872) ~[je-7.3.7.jar:7.3.7]
	at com.sleepycat.je.rep.impl.node.Replay.replayEntry(Replay.java:598) ~[je-7.3.7.jar:7.3.7]
	at com.sleepycat.je.rep.impl.node.Replica$ReplayThread.run(Replica.java:1213) ~[je-7.3.7.jar:7.3.7]
2020-08-21 02:05:01,916 WARN 91 [DefaultChannelPipeline.onUnhandledInboundException():1164] An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception.
java.io.IOException: 打开的文件过多
	at sun.nio.ch.ServerSocketChannelImpl.accept0(Native Method) ~[?:1.8.0_251]
	at sun.nio.ch.ServerSocketChannelImpl.accept(ServerSocketChannelImpl.java:422) ~[?:1.8.0_251]
	at sun.nio.ch.ServerSocketChannelImpl.accept(ServerSocketChannelImpl.java:250) ~[?:1.8.0_251]
	at io.netty.util.internal.SocketUtils$5.run(SocketUtils.java:110) ~[netty-all-4.1.42.Final.jar:4.1.42.Final]
	at io.netty.util.internal.SocketUtils$5.run(SocketUtils.java:107) ~[netty-all-4.1.42.Final.jar:4.1.42.Final]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_251]
	at io.netty.util.internal.SocketUtils.accept(SocketUtils.java:107) ~[netty-all-4.1.42.Final.jar:4.1.42.Final]
	at io.netty.channel.socket.nio.NioServerSocketChannel.doReadMessages(NioServerSocketChannel.java:145) ~[netty-all-4.1.42.Final.jar:4.1.42.Final]
	at io.netty.channel.nio.AbstractNioMessageChannel$NioMessageUnsafe.read(AbstractNioMessageChannel.java:75) [netty-all-4.1.42.Final.jar:4.1.42.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:700) [netty-all-4.1.42.Final.jar:4.1.42.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:635) [netty-all-4.1.42.Final.jar:4.1.42.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:552) [netty-all-4.1.42.Final.jar:4.1.42.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:514) [netty-all-4.1.42.Final.jar:4.1.42.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$6.run(SingleThreadEventExecutor.java:1044) [netty-all-4.1.42.Final.jar:4.1.42.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [netty-all-4.1.42.Final.jar:4.1.42.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [netty-all-4.1.42.Final.jar:4.1.42.Final]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_251]






be log
W0821 02:07:52.890352 153176 data_dir.cpp:769] find invalid rowset: 02000000000023ee8a483bdf80b47c4b5cdc7c1b0032a58c with tablet id: 351315 tablet uid: ad4358bce6bc1436-539566e9422393af schema hash: 818975579 txn: 140583 current valid tablet uid: f545d14ba86715c9-4f23a24a452bda8b
W0821 02:07:52.890357 153176 data_dir.cpp:769] find invalid rowset: 02000000000023f78a483bdf80b47c4b5cdc7c1b0032a58c with tablet id: 351315 tablet uid: ad4358bce6bc1436-539566e9422393af schema hash: 818975579 txn: 140598 current valid tablet uid: f545d14ba86715c9-4f23a24a452bda8b
W0821 02:07:52.890364 153176 data_dir.cpp:769] find invalid rowset: 02000000000024018a483bdf80b47c4b5cdc7c1b0032a58c with tablet id: 351315 tablet uid: ad4358bce6bc1436-539566e9422393af schema hash: 818975579 txn: 140599 current valid tablet uid: f545d14ba86715c9-4f23a24a452bda8b
W0821 02:07:52.890370 153176 data_dir.cpp:769] find invalid rowset: 020000000000240b8a483bdf80b47c4b5cdc7c1b0032a58c with tablet id: 351315 tablet uid: ad4358bce6bc1436-539566e9422393af schema hash: 818975579 txn: 140600 current valid tablet uid: f545d14ba86715c9-4f23a24a452bda8b
W0821 02:07:52.890377 153176 data_dir.cpp:769] find invalid rowset: 02000000000024158a483bdf80b47c4b5cdc7c1b0032a58c with tablet id: 351315 tablet uid: ad4358bce6bc1436-539566e9422393af schema hash: 818975579 txn: 140601 current valid tablet uid: f545d14ba86715c9-4f23a24a452bda8b
W0821 02:07:52.890386 153176 data_dir.cpp:769] find invalid rowset: 020000000000241f8a483bdf80b47c4b5cdc7c1b0032a58c with tablet id: 351315 tablet uid: ad4358bce6bc1436-539566e9422393af schema hash: 818975579 txn: 140613 current valid tablet uid: f545d14ba86715c9-4f23a24a452bda8b
W0821 02:07:52.890393 153176 data_dir.cpp:769] find invalid rowset: 02000000000024288a483bdf80b47c4b5cdc7c1b0032a58c with tablet id: 351315 tablet uid: ad4358bce6bc1436-539566e9422393af schema hash: 818975579 txn: 140614 current valid tablet uid: f545d14ba86715c9-4f23a24a452bda8b
W0821 02:07:52.890401 153176 data_dir.cpp:769] find invalid rowset: 02000000000024328a483bdf80b47c4b5cdc7c1b0032a58c with tablet id: 351315 tablet uid: ad4358bce6bc1436-539566e9422393af schema hash: 818975579 txn: 140615 current valid tablet uid: f545d14ba86715c9-4f23a24a452bda8b
W0821 02:07:52.890408 153176 data_dir.cpp:769] find invalid rowset: 020000000000243b8a483bdf80b47c4b5cdc7c1b0032a58c with tablet id: 351315 tablet uid: ad4358bce6bc1436-539566e9422393af schema hash: 818975579 txn: 140616 current valid tablet uid: f545d14ba86715c9-4f23a24a452bda8b
W0821 02:07:52.890414 153176 data_dir.cpp:725] could not find tablet id: 815207731, schema hash: 1436542443, for rowset: 020000000007de99b84986b19ec400f2a2c578843f998da7, skip this rowset
W0821 02:07:52.890421 153176 data_dir.cpp:725] could not find tablet id: 815207881, schema hash: 1436542443, for rowset: 020000000007debbb84986b19ec400f2a2c578843f998da7, skip this rowset
W0821 02:07:52.890427 153176 data_dir.cpp:725] could not find tablet id: 329553, schema hash: 1796958200, for rowset: 02000000000119fc564ba54d4859d5822f31ad0d4dd7e397, skip this rowset
W0821 02:07:52.890432 153176 data_dir.cpp:725] could not find tablet id: 329553, schema hash: 1796958200, for rowset: 0200000000011a00564ba54d4859d5822f31ad0d4dd7e397, skip this rowset
W0821 02:07:52.890439 153176 data_dir.cpp:725] could not find tablet id: 329553, schema hash: 1796958200, for rowset: 0200000000011a06564ba54d4859d5822f31ad0d4dd7e397, skip this rowset
```

**Desktop (please complete the following information):**
 - OS: centos 7
 - 0.12

**Additional context**

**Comment by morningman** [comment]
`java.io.IOException: 打开的文件过多`

Looks like encounter `too many open files`? Have you deploy FE and BE on same host?

**Comment by francisoliverlee** [comment]
> `java.io.IOException: 打开的文件过多`
> 
> Looks like encounter `too many open files`? Have you deploy FE and BE on same host?

no

**Comment by francisoliverlee** [comment]
may it possible when be dead, FE hold conections, so there are a lot of dead conections not to be release.

**Comment by wuyunfeng** [comment]
Can you provide the abstract content of `ll /proc/{fe pid}/fd`

**Comment by francisoliverlee** [comment]
> Can you provide the abstract content of `ll /proc/{fe pid}/fd`

so long that we had restarted the cluster to recover

**Comment by wuyunfeng** [comment]
@francisoliverlee  emm, I would close this issue. if you have same issue with this, feel free to reopen this issue. 
The next time  you can provide some statistical information about the opened `fd`

**Comment by francisoliverlee** [comment]
ll /proc/26123/fd
count is 65535, and

netstat -antp | grep 9030
there are a 300+ other fe instance connections but CLOSE_WAIT.  but there are 6 fe

**Comment by wuyunfeng** [comment]
the rest about `65535 - 300+` is what type `fd`?

**Comment by francisoliverlee** [comment]
socket

**Comment by francisoliverlee** [comment]
@wuyunfeng finally i find-it. it's nginx.
nginx hold a lot of close_wait tcp connections,  that makes fe's fd count hit that max open-file-count 65535. i changed the nginx config, and waiting check

**Comment by wuyunfeng** [comment]
@francisoliverlee That's nice. Maybe you can set smaller value for keepalive_timeout?

**Comment by francisoliverlee** [comment]
> @francisoliverlee That's nice. Maybe you can set smaller value for keepalive_timeout?

ok, i will try it and tks!
