### ISSUE TITLE
Doris should support Update table statement.

### ISSUE THREAD

**Issue by mmuru** [apache/incubator-doris#4799]
**Is your feature request related to a problem? Please describe.**
Currently, Doris does not support update table. It throws the exception when we perform update on any data model tables. 
 Like any SQL databases, the update table should be supported in Doris.

**Describe the solution you'd like**
Like Apache Impala supports update table statement. Hence, Apache Doris should support update table statement in all data model tables. I believe, update is being supported implicitly within Apache Doris.

**Describe alternatives you've considered**
N/A

**Additional context**
`
2020-10-06 17:41:09,617 WARN (doris-mysql-nio-pool-82|684) [ConnectProcessor.analyze():243] origin_stmt: update table1 set username='muru' where siteid=5; Analyze error message: Syntax error in line 1:
update table1 set username='muru' where siteid=5
^
Encountered: IDENTIFIER
Expected
org.apache.doris.common.AnalysisException: errCode = 2, detailMessage = Syntax error
        at org.apache.doris.analysis.SqlParser.unrecovered_syntax_error(SqlParser.java:1749) ~[palo-fe.jar:3.4.0]
        at java_cup.runtime.lr_parser.parse(lr_parser.java:616) ~[jflex-1.4.3.jar:?]
        at org.apache.doris.common.util.SqlParserUtils.getMultiStmts(SqlParserUtils.java:50) ~[palo-fe.jar:3.4.0]
        at org.apache.doris.qe.ConnectProcessor.analyze(ConnectProcessor.java:239) ~[palo-fe.jar:3.4.0]
        at org.apache.doris.qe.ConnectProcessor.handleQuery(ConnectProcessor.java:183) ~[palo-fe.jar:3.4.0]
        at org.apache.doris.qe.ConnectProcessor.dispatch(ConnectProcessor.java:325) ~[palo-fe.jar:3.4.0]
        at org.apache.doris.qe.ConnectProcessor.processOnce(ConnectProcessor.java:510) ~[palo-fe.jar:3.4.0]
        at org.apache.doris.mysql.nio.ReadListener.lambda$handleEvent$0(ReadListener.java:50) ~[palo-fe.jar:3.4.0]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_262]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_262]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_262]
`

**Comment by morningman** [comment]
Does UPDATE command in Impala only support KUDU table?

This function is limited by the implementation of the underlying storage engine.
The Kudu engine supports the update function, while the Doris storage engine currently does not support update.
We are working hard in this direction, but it is difficult to have a perfect solution in the short term.

**Comment by yiguolei** [comment]
@morningman How about implement Update Where Stmt as a alter job？

**Comment by morningman** [comment]
> @morningman How about implement Update Where Stmt as a alter job？

If so, currently we can only do it in UNIQUE_KEY model, and the performance can not be guaranteed.
