### ISSUE TITLE
数据写入错误Tablet [11400] success replica num 0 is less then quorum replica num 1 while error backends 10003

### ISSUE THREAD

**Issue by ningyanhui** [apache/incubator-doris#4910]
use pyspark write dorisDB,

data_result.repartition(1).write.format("jdbc").\
    mode(saveMode='append').option("url", "jdbc:mysql://192.168.108.192:9030/test")\
    .option("dbtable", "test")\
    .option("user", "root")\
    .option("password", "")\
    .save()

ERROR:
Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: errCode = 2, detailMessage = Failed to commit txn 20196. Tablet [11400] success replica num 0 is less then quorum replica num 1 while error backends 10003
        at sun.reflect.GeneratedConstructorAccessor14.newInstance(Unknown Source)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
        at com.mysql.jdbc.Util.getInstance(Util.java:408)
        at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:943)
        at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3973)
        at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3909)
        at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2527)
        at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2680)
        at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2490)
        at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1858)
        at com.mysql.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2079)
        at com.mysql.jdbc.PreparedStatement.executeBatchSerially(PreparedStatement.java:1756)
        ... 15 more

**Comment by rookieuncle** [comment]
请问 怎么解决的？

**Comment by michael1991** [comment]
+1， 请问怎么解决的？
