### ISSUE TITLE
Observer failed and can not work

### ISSUE THREAD

**Issue by caiconghui** [apache/incubator-doris#5082]
2020-12-15 16:31:30,537 WARN 81 [BDBEnvironment.getDatabaseNames():328] bdb environment failure exception. will retry
com.sleepycat.je.EnvironmentFailureException: (JE 7.3.7) Environment must be closed, caused by: com.sleepycat.je.EnvironmentFailureException: Environment invalid because of previous exception: (JE 7.3.7) 10.118.32.27_9010_1607949117395(2147483646):/home/work/app/doris/c3prc-ga/fe/hdd/bdb com.sleepycat.je.log.ChecksumException: Invalid log entry type: 0 lsn=0xb4a4/0x915153 bufPosition=5464 bufRemaining=18088 LOG_CHECKSUM: Checksum invalid on read, log is likely invalid. Environment is invalid and must be closed. Originally thrown by HA thread: REPLICA 10.118.32.27_9010_1607949117395(2147483646)
        at com.sleepycat.je.EnvironmentFailureException.wrapSelf(EnvironmentFailureException.java:228) ~[je-7.3.7.jar:7.3.7]
        at com.sleepycat.je.dbi.EnvironmentImpl.checkIfInvalid(EnvironmentImpl.java:1766) ~[je-7.3.7.jar:7.3.7]
        at com.sleepycat.je.dbi.EnvironmentImpl.checkOpen(EnvironmentImpl.java:1775) ~[je-7.3.7.jar:7.3.7]
        at com.sleepycat.je.Environment.checkOpen(Environment.java:2473) ~[je-7.3.7.jar:7.3.7]
        at com.sleepycat.je.Environment.getDatabaseNames(Environment.java:2245) ~[je-7.3.7.jar:7.3.7]
        at org.apache.doris.journal.bdbje.BDBEnvironment.getDatabaseNames(BDBEnvironment.java:318) [palo-fe.jar:?]
        at org.apache.doris.journal.bdbje.BDBJEJournal.getMaxJournalId(BDBJEJournal.java:258) [palo-fe.jar:?]
        at org.apache.doris.persist.EditLog.getMaxJournalId(EditLog.java:94) [palo-fe.jar:?]
        at org.apache.doris.catalog.Catalog.getMaxJournalId(Catalog.java:4676) [palo-fe.jar:?]
        at org.apache.doris.catalog.Catalog.replayJournal(Catalog.java:2393) [palo-fe.jar:?]
        at org.apache.doris.catalog.Catalog$3.runOneCycle(Catalog.java:2198) [palo-fe.jar:?]
        at org.apache.doris.common.util.Daemon.run(Daemon.java:116) [palo-fe.jar:?]
Caused by: com.sleepycat.je.EnvironmentFailureException: Environment invalid because of previous exception: (JE 7.3.7) 10.118.32.27_9010_1607949117395(2147483646):/home/work/app/doris/c3prc-ga/fe/hdd/bdb com.sleepycat.je.log.ChecksumException: Invalid log entry type: 0 lsn=0xb4a4/0x915153 bufPosition=5464 bufRemaining=18088 LOG_CHECKSUM: Checksum invalid on read, log is likely invalid. Environment is invalid and must be closed. Originally thrown by HA thread: REPLICA 10.118.32.27_9010_1607949117395(2147483646)
        at com.sleepycat.je.cleaner.FileProcessor.processFile(FileProcessor.java:1028) ~[je-7.3.7.jar:7.3.7]
        at com.sleepycat.je.cleaner.FileProcessor.doClean(FileProcessor.java:478) ~[je-7.3.7.jar:7.3.7]
        at com.sleepycat.je.cleaner.FileProcessor.onWakeup(FileProcessor.java:286) ~[je-7.3.7.jar:7.3.7]
        at com.sleepycat.je.utilint.DaemonThread.run(DaemonThread.java:154) ~[je-7.3.7.jar:7.3.7]
        at java.lang.Thread.run(Thread.java:834) ~[?:?]
Caused by: com.sleepycat.je.log.ChecksumException: Invalid log entry type: 0 lsn=0xb4a4/0x915153 bufPosition=5464 bufRemaining=18088
        at com.sleepycat.je.log.LogEntryHeader.<init>(LogEntryHeader.java:173) ~[je-7.3.7.jar:7.3.7]
        at com.sleepycat.je.log.FileReader.readBasicHeader(FileReader.java:633) ~[je-7.3.7.jar:7.3.7]
        at com.sleepycat.je.log.FileReader.readNextEntryAllowExceptions(FileReader.java:279) ~[je-7.3.7.jar:7.3.7]
        at com.sleepycat.je.cleaner.FileProcessor.processFile(FileProcessor.java:724) ~[je-7.3.7.jar:7.3.7]
        at com.sleepycat.je.cleaner.FileProcessor.doClean(FileProcessor.java:478) ~[je-7.3.7.jar:7.3.7]
        at com.sleepycat.je.cleaner.FileProcessor.onWakeup(FileProcessor.java:286) ~[je-7.3.7.jar:7.3.7]
        at com.sleepycat.je.utilint.DaemonThread.run(DaemonThread.java:154) ~[je-7.3.7.jar:7.3.7]
        at java.lang.Thread.run(Thread.java:834) ~[?:?]

**Comment by caiconghui** [comment]
We have encountered the above problem twice， and have no idea.

**Comment by caiconghui** [comment]
we found bad sectors in the hard disk caused the corruption. so the observer failed
