### ISSUE TITLE
[BUG] StringType can not transform to DateType when read hive table to doris by spark load

### ISSUE THREAD

**Issue by Dam1029** [apache/incubator-doris#5224]
**Describe the bug**
I test doris global dictionary function by spark load.  The partition field in hive table is String type and the corresponding field in doris table is DATE type. Then I submitted a spark load job, but the job failed and I got the error message.

```
spark etl job run failed
org.apache.spark.SparkException: Job aborted due to stage failure: Task 15 in stage 13.0 failed 4 times, most recent failure: Lost task 15.3 in stage 13.0 (TID 1370, plat-data-hadoop-pro334, executor 21): java.lang.RuntimeException: Error while encoding: java.lang.RuntimeException: java.lang.String is not a valid external type for schema of date
staticinvoke(class org.apache.spark.sql.catalyst.util.DateTimeUtils$, DateType, fromJavaDate, validateexternaltype(getexternalrowfield(assertnotnull(input[0, org.apache.spark.sql.Row, true]), 0, logdate), DateType), true, false) AS logdate#240
validateexternaltype(getexternalrowfield(assertnotnull(input[0, org.apache.spark.sql.Row, true]), 1, app_id), IntegerType) AS app_id#241
staticinvoke(class org.apache.spark.unsafe.types.UTF8String, StringType, fromString, validateexternaltype(getexternalrowfield(assertnotnull(input[0, org.apache.spark.sql.Row, true]), 2, game), StringType), true, false) AS game#242
if (assertnotnull(input[0, org.apache.spark.sql.Row, true]).isNullAt) null else staticinvoke(class org.apache.spark.unsafe.types.UTF8String, StringType, fromString, validateexternaltype(getexternalrowfield(assertnotnull(input[0, org.apache.spark.sql.Row, true]), 3, event_action), StringType), true, false) AS event_action#243
if (assertnotnull(input[0, org.apache.spark.sql.Row, true]).isNullAt) null else staticinvoke(class org.apache.spark.unsafe.types.UTF8String, StringType, fromString, validateexternaltype(getexternalrowfield(assertnotnull(input[0, org.apache.spark.sql.Row, true]), 4, event_category), StringType), true, false) AS event_category#244
if (assertnotnull(input[0, org.apache.spark.sql.Row, true]).isNullAt) null else staticinvoke(class org.apache.spark.unsafe.types.UTF8String, StringType, fromString, validateexternaltype(getexternalrowfield(assertnotnull(input[0, org.apache.spark.sql.Row, true]), 5, event_label), StringType), true, false) AS event_label#245
if (assertnotnull(input[0, org.apache.spark.sql.Row, true]).isNullAt) null else staticinvoke(class org.apache.spark.unsafe.types.UTF8String, StringType, fromString, validateexternaltype(getexternalrowfield(assertnotnull(input[0, org.apache.spark.sql.Row, true]), 6, event_value), StringType), true, false) AS event_value#246
if (assertnotnull(input[0, org.apache.spark.sql.Row, true]).isNullAt) null else validateexternaltype(getexternalrowfield(assertnotnull(input[0, org.apache.spark.sql.Row, true]), 7, game_level), IntegerType) AS game_level#247
if (assertnotnull(input[0, org.apache.spark.sql.Row, true]).isNullAt) null else validateexternaltype(getexternalrowfield(assertnotnull(input[0, org.apache.spark.sql.Row, true]), 8, game_vip_level), IntegerType) AS game_vip_level#248
if (assertnotnull(input[0, org.apache.spark.sql.Row, true]).isNullAt) null else validateexternaltype(getexternalrowfield(assertnotnull(input[0, org.apache.spark.sql.Row, true]), 9, game_tag), IntegerType) AS game_tag#249
if (assertnotnull(input[0, org.apache.spark.sql.Row, true]).isNullAt) null else validateexternaltype(getexternalrowfield(assertnotnull(input[0, org.apache.spark.sql.Row, true]), 10, event_ts), LongType) AS event_ts#250L
staticinvoke(class org.apache.spark.unsafe.types.UTF8String, StringType, fromString, validateexternaltype(getexternalrowfield(assertnotnull(input[0, org.apache.spark.sql.Row, true]), 11, uuid), StringType), true, false) AS uuid#251
	at org.apache.spark.sql.catalyst.encoders.ExpressionEncoder.toRow(ExpressionEncoder.scala:292)
	at org.apache.spark.sql.SparkSession$$anonfun$4.apply(SparkSession.scala:593)
	at org.apache.spark.sql.SparkSession$$anonfun$4.apply(SparkSession.scala:593)
	at scala.collection.Iterator$$anon$11.next(Iterator.scala:410)
	at scala.collection.Iterator$$anon$11.next(Iterator.scala:410)
	at scala.collection.Iterator$$anon$11.next(Iterator.scala:410)
	at scala.collection.Iterator$$anon$11.next(Iterator.scala:410)
	at scala.collection.Iterator$$anon$12.nextCur(Iterator.scala:435)
	at scala.collection.Iterator$$anon$12.hasNext(Iterator.scala:441)
	at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:409)
	at org.apache.spark.util.collection.ExternalSorter.insertAll(ExternalSorter.scala:191)
	at org.apache.spark.shuffle.sort.SortShuffleWriter.write(SortShuffleWriter.scala:62)
	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:99)
	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:55)
	at org.apache.spark.scheduler.Task.run(Task.scala:121)
	at org.apache.spark.executor.Executor$TaskRunner$$anonfun$10.apply(Executor.scala:408)
	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1360)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:414)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.RuntimeException: java.lang.String is not a valid external type for schema of date
	at org.apache.spark.sql.catalyst.expressions.GeneratedClass$SpecificUnsafeProjection.StaticInvoke_0$(Unknown Source)
	at org.apache.spark.sql.catalyst.expressions.GeneratedClass$SpecificUnsafeProjection.writeFields_0_0$(Unknown Source)
	at org.apache.spark.sql.catalyst.expressions.GeneratedClass$SpecificUnsafeProjection.apply(Unknown Source)
	at org.apache.spark.sql.catalyst.encoders.ExpressionEncoder.toRow(ExpressionEncoder.scala:289)
	... 20 more

Driver stacktrace:
	at org.apache.spark.scheduler.DAGScheduler.org$apache$spark$scheduler$DAGScheduler$$failJobAndIndependentStages(DAGScheduler.scala:1889)
	at org.apache.spark.scheduler.DAGScheduler$$anonfun$abortStage$1.apply(DAGScheduler.scala:1877)
	at org.apache.spark.scheduler.DAGScheduler$$anonfun$abortStage$1.apply(DAGScheduler.scala:1876)
	at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:48)
	at org.apache.spark.scheduler.DAGScheduler.abortStage(DAGScheduler.scala:1876)
	at org.apache.spark.scheduler.DAGScheduler$$anonfun$handleTaskSetFailed$1.apply(DAGScheduler.scala:926)
	at org.apache.spark.scheduler.DAGScheduler$$anonfun$handleTaskSetFailed$1.apply(DAGScheduler.scala:926)
	at scala.Option.foreach(Option.scala:257)
	at org.apache.spark.scheduler.DAGScheduler.handleTaskSetFailed(DAGScheduler.scala:926)
	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.doOnReceive(DAGScheduler.scala:2110)
	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:2059)
	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:2048)
	at org.apache.spark.util.EventLoop$$anon$1.run(EventLoop.scala:49)
	at org.apache.spark.scheduler.DAGScheduler.runJob(DAGScheduler.scala:737)
	at org.apache.spark.SparkContext.runJob(SparkContext.scala:2061)
	at org.apache.spark.SparkContext.runJob(SparkContext.scala:2082)
	at org.apache.spark.SparkContext.runJob(SparkContext.scala:2101)
	at org.apache.spark.SparkContext.runJob(SparkContext.scala:2126)
	at org.apache.spark.rdd.RDD$$anonfun$foreachPartition$1.apply(RDD.scala:935)
	at org.apache.spark.rdd.RDD$$anonfun$foreachPartition$1.apply(RDD.scala:933)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:151)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:112)
	at org.apache.spark.rdd.RDD.withScope(RDD.scala:363)
	at org.apache.spark.rdd.RDD.foreachPartition(RDD.scala:933)
	at org.apache.spark.api.java.JavaRDDLike$class.foreachPartition(JavaRDDLike.scala:219)
	at org.apache.spark.api.java.AbstractJavaRDDLike.foreachPartition(JavaRDDLike.scala:45)
	at org.apache.doris.load.loadv2.dpp.SparkDpp.writeRepartitionAndSortedRDDToParquet(SparkDpp.java:194)
	at org.apache.doris.load.loadv2.dpp.SparkDpp.processRollupTree(SparkDpp.java:332)
	at org.apache.doris.load.loadv2.dpp.SparkDpp.process(SparkDpp.java:1014)
	at org.apache.doris.load.loadv2.dpp.SparkDpp.doDpp(SparkDpp.java:1050)
	at org.apache.doris.load.loadv2.etl.SparkEtlJob.processDpp(SparkEtlJob.java:142)
	at org.apache.doris.load.loadv2.etl.SparkEtlJob.processData(SparkEtlJob.java:226)
	at org.apache.doris.load.loadv2.etl.SparkEtlJob.run(SparkEtlJob.java:233)
	at org.apache.doris.load.loadv2.etl.SparkEtlJob.main(SparkEtlJob.java:243)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.spark.deploy.yarn.ApplicationMaster$$anon$2.run(ApplicationMaster.scala:684)
Caused by: java.lang.RuntimeException: Error while encoding: java.lang.RuntimeException: java.lang.String is not a valid external type for schema of date

```

**Expected behavior**
The String type field can be transform to DATE type  automatically.

**Screenshots**
In the function convertSrcDataframeToDstDataframe(xxx), it seem to do transform string to date, but it can not work.

![image](https://user-images.githubusercontent.com/26566636/104296590-c6e01c80-54fc-11eb-8d5a-92f69f6a7b5a.png)
![image](https://user-images.githubusercontent.com/26566636/104296357-7bc60980-54fc-11eb-94a4-d4a2be033ea7.png)
![image](https://user-images.githubusercontent.com/26566636/104296386-81235400-54fc-11eb-8cd8-bf97d832444c.png)

**Desktop (please complete the following information):**
 - OS: [centos7]
 - Version [0.13.0-rc03 ]

**Comment by wangbo** [comment]
Please add hive's table schema and doris's table schema.
And the what's the screenshots's content, my chrome can't load the image even using cellphone with 4G

**Comment by Dam1029** [comment]
> Please add hive's table schema and doris's table schema.
> And the what's the screenshots's content, my chrome can't load the image even using cellphone with 4G

```
CREATE EXTERNAL TABLE `hive_h5_event_info`(
  `logdate` varchar(100) NULL COMMENT "时间",
  `region` varchar(100) NULL COMMENT "地域",
  `app_id` int(11) NOT NULL COMMENT "活动id",
  `user` varchar(25) NOT NULL COMMENT "",
  `event_action` varchar(255) NULL DEFAULT "" COMMENT "",
  `event_category` varchar(255) NULL DEFAULT "" COMMENT "",
  `event_label` varchar(255) NULL DEFAULT "" COMMENT "",
  `event_value` varchar(255) NULL DEFAULT "" COMMENT "",
  `user_level` int(11) NULL DEFAULT "0" COMMENT "",
  `user_vip_level` int(11) NULL DEFAULT "0" COMMENT "",
  `user_tag` int(11) NULL DEFAULT "0" COMMENT "",
  `event_ts` bigint(20) NULL DEFAULT "0" COMMENT "",
  `uuid` varchar(50) NOT NULL COMMENT ""
)
ENGINE=hive
PROPERTIES
(
   "database" = "xxx",
   "table" = "xxx",
   "hive.metastore.uris" = "xxx"
);
```

```
CREATE TABLE `global_dict_h5_event_info` (
  `logdate` date NOT NULL COMMENT "分区日期",
  `app_id` int(11) NOT NULL COMMENT "活动id",
  `user` varchar(25) NOT NULL COMMENT "",
  `event_action` varchar(255) NULL DEFAULT "" COMMENT "",
  `event_category` varchar(255) NULL DEFAULT "" COMMENT "",
  `event_label` varchar(255) NULL DEFAULT "" COMMENT "",
  `event_value` varchar(255) NULL DEFAULT "" COMMENT "",
  `user_level` int(11) NULL DEFAULT "0" COMMENT "",
  `user_vip_level` int(11) NULL DEFAULT "0" COMMENT "",
  `user_tag` int(11) NULL DEFAULT "0" COMMENT "",
  `event_ts` bigint(20) NULL DEFAULT "0" COMMENT "",
  `uuid` bitmap BITMAP_UNION NOT NULL COMMENT ""
) ENGINE=OLAP
AGGREGATE KEY(`logdate`, `app_id`, `user`, `event_action`, `event_category`, `event_label`, `event_value`, `user_level`, `user_vip_level`, `user_tag`, `event_ts`)
COMMENT "OLAP"
PARTITION BY RANGE(`logdate`)
()
DISTRIBUTED BY HASH(`logdate`) BUCKETS 10
PROPERTIES (
"replication_num" = "3",
"dynamic_partition.enable" = "true",
"dynamic_partition.time_unit" = "DAY",
"dynamic_partition.start" = "-2147483648",
"dynamic_partition.end" = "2",
"dynamic_partition.prefix" = "p",
"dynamic_partition.replication_num" = "3",
"dynamic_partition.buckets" = "12",
"in_memory" = "false",
"storage_format" = "V2"
);
```


```
LOAD LABEL test.global_dict_h5_event_info
(   DATA FROM TABLE hive_h5_event_info
    INTO TABLE global_dict_h5_event_info
    SET(logdate=logdate,game=game,event_action=event_action,event_category=event_category,event_label=event_label,
    event_value=event_value,game_level=game_level,game_vip_level=game_vip_level,game_tag=game_tag,event_ts=event_ts,uuid=bitmap_dict(uuid)))
WITH RESOURCE 'spark'
(
    "spark.executor.memory" = "10g",
    "spark.executor.instances" = "30",
    "spark.shuffle.compress" = "true"
)
PROPERTIES
("timeout" = "3600");
```

**Comment by Dam1029** [comment]
> Please add hive's table schema and doris's table schema.
> And the what's the screenshots's content, my chrome can't load the image even using cellphone with 4G

The screenshots's content is some functions  in SparkDpp, Which I think may be exsit bug. They are processRollupTree(xxx), writeRepartitionAndSortedRDDToParquet(xxx) and convertSrcDataframeToDstDataframe(xxx).
