### ISSUE TITLE
Node catalog is not ready, please wait for a while.

### ISSUE THREAD

**Issue by hf200012** [apache/incubator-doris#5396]
Doris version ：0.13.11

Three FEs are operating normally, BE is operating normally
This exception frequently occurs today, and the exception information is as follows:

java.net.SocketException: Socket closed
 at java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:118)
 at java.net.SocketOutputStream.write(SocketOutputStream.java:155)
 at java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:82)
 at java.io.BufferedOutputStream.flush(BufferedOutputStream.java:140)
 at java.io.FilterOutputStream.close(FilterOutputStream.java:158)
 at org.apache.thrift.transport.TIOStreamTransport.close(TIOStreamTransport.java:110)
 at org.apache.thrift.transport.TSocket.close(TSocket.java:235)
 at org.apache.thrift.server.TThreadPoolServer$WorkerProcess.run(TThreadPoolServer.java:303)
 at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
 at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
 at java.lang.Thread.run(Thread.java:748)
2021-02-19 17:12:55 WARN  TIOStreamTransport:112 - Error closing output stream

Master  FE Exception：
2021-02-19 17:38:17,897 WARN (doris-mysql-nio-pool-5511|17410) [ReadListener.lambda$handleEvent$0():58] Exception happened in one session(org.apache.doris.mysql.nio.NConnectContext@538b80ad).
java.io.IOException: Error happened when receiving packet.
 at org.apache.doris.qe.ConnectProcessor.processOnce(ConnectProcessor.java:499) ~[palo-fe.jar:3.4.0]
 at org.apache.doris.mysql.nio.ReadListener.lambda$handleEvent$0(ReadListener.java:50) ~[palo-fe.jar:3.4.0]
 at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_261]
 at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_261]
 at java.lang.Thread.run(Thread.java:748) [?:1.8.0_261]
2021-02-19 17:38:18,930 WARN (doris-mysql-nio-pool-5511|17410) [ConnectProcessor.dispatch():334] Unsupported command(Change user)
2021-02-19 17:38:18,931 WARN (doris-mysql-nio-pool-5511|17410) [ConnectProcessor.processOnce():498] Null packet received from network. remote: 172.22.197.238:39554
2021-02-19 17:38:18,931 WARN (doris-mysql-nio-pool-5511|17410) [ReadListener.lambda$handleEvent$0():58] Exception happened in one session(org.apache.doris.mysql.nio.NConnectContext@3a85c035).
java.io.IOException: Error happened when receiving packet.
 at org.apache.doris.qe.ConnectProcessor.processOnce(ConnectProcessor.java:499) ~[palo-fe.jar:3.4.0]
 at org.apache.doris.mysql.nio.ReadListener.lambda$handleEvent$0(ReadListener.java:50) ~[palo-fe.jar:3.4.0]
 at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_261]
 at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_261]
 at java.lang.Thread.run(Thread.java:748) [?:1.8.0_261]

**Comment by hf200012** [comment]
The reason for this exception is that the thrift rpc communication is abnormal, which causes a big difference in ReplayedJournalId

**Comment by mie-hei** [comment]
@hf200012 你好 ，请问你是怎么解决这个问题的呀

**Comment by koooolllll** [comment]
@hf200012 +1，请问是怎么解决这个问题的呢
