### ISSUE TITLE
[Bug] A NumberFormatException exception throwed when FE start

### ISSUE THREAD

**Issue by acelyc111** [apache/incubator-doris#5415]
**Describe the bug**
When we add a new OBSERVER FE into an already running a long time cluster, the new FE throw exception like:
```
2021-02-24 17:09:22,696 ERROR 1 [BDBJEJournal.open():319] catch an exception when setup bdb environment. will exit.
java.lang.NumberFormatException: For input string: "2225350428"
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65) ~[?:?]
	at java.lang.Integer.parseInt(Integer.java:652) ~[?:?]
	at java.lang.Integer.parseInt(Integer.java:770) ~[?:?]
	at com.sleepycat.je.rep.InsufficientLogException.<init>(InsufficientLogException.java:218) ~[je-7.3.7.jar:7.3.7]
	at com.sleepycat.je.rep.impl.RepImpl.handleRestoreRequired(RepImpl.java:2296) ~[je-7.3.7.jar:7.3.7]
	at com.sleepycat.je.recovery.RecoveryManager.findEndOfLog(RecoveryManager.java:543) ~[je-7.3.7.jar:7.3.7]
	at com.sleepycat.je.recovery.RecoveryManager.recover(RecoveryManager.java:339) ~[je-7.3.7.jar:7.3.7]
	at com.sleepycat.je.dbi.EnvironmentImpl.finishInit(EnvironmentImpl.java:841) ~[je-7.3.7.jar:7.3.7]
	at com.sleepycat.je.dbi.DbEnvPool.getEnvironment(DbEnvPool.java:222) ~[je-7.3.7.jar:7.3.7]
	at com.sleepycat.je.Environment.makeEnvironmentImpl(Environment.java:267) ~[je-7.3.7.jar:7.3.7]
	at com.sleepycat.je.Environment.<init>(Environment.java:252) ~[je-7.3.7.jar:7.3.7]
	at com.sleepycat.je.rep.ReplicatedEnvironment.<init>(ReplicatedEnvironment.java:607) ~[je-7.3.7.jar:7.3.7]
	at com.sleepycat.je.rep.ReplicatedEnvironment.<init>(ReplicatedEnvironment.java:466) ~[je-7.3.7.jar:7.3.7]
	at com.sleepycat.je.rep.ReplicatedEnvironment.<init>(ReplicatedEnvironment.java:540) ~[je-7.3.7.jar:7.3.7]
	at org.apache.doris.journal.bdbje.BDBEnvironment.setup(BDBEnvironment.java:149) ~[palo-fe.jar:?]
	at org.apache.doris.journal.bdbje.BDBJEJournal.open(BDBJEJournal.java:316) [palo-fe.jar:?]
	at org.apache.doris.persist.EditLog.open(EditLog.java:788) [palo-fe.jar:?]
	at org.apache.doris.catalog.Catalog.initialize(Catalog.java:733) [palo-fe.jar:?]
	at org.apache.doris.PaloFe.start(PaloFe.java:111) [palo-fe.jar:?]
	at org.apache.doris.PaloFe.main(PaloFe.java:60) [palo-fe.jar:?]
```
I checked the code of [bdb-je 7.3.7](https://github.com/bantudb/je), it seems it's **int** overflowed in [code](https://github.com/bantudb/je/blob/master/src/com/sleepycat/je/rep/InsufficientLogException.java#L218)

The latest version of bdb-je has fixed the bug:
[change log](https://docs.oracle.com/cd/E17277_02/html/changelog.html):
```
Fixed a bug that could prevent performing a network restore (NetworkRestore.execute), after a prior network restore was aborted or incomplete for any reason. For example, this could occur if the process is killed during the first network restore, and then another network restore is attempted. The problem could occur only in an environment with a relatively large data set, specifically where at least one billion write transactions had been performed. An example stack trace is below.
java.lang.NumberFormatException: For input string: "7473413648"
    at java.lang.NumberFormatException.forInputString(
        NumberFormatException.java:65)
    at java.lang.Integer.parseInt(Integer.java:583)
    at java.lang.Integer.parseInt(Integer.java:615)
    at com.sleepycat.je.rep.InsufficientLogException.init(
        InsufficientLogException.java:218)
    at com.sleepycat.je.rep.impl.RepImpl.handleRestoreRequired(
        RepImpl.java:2296)
    at com.sleepycat.je.recovery.RecoveryManager.findEndOfLog(
        RecoveryManager.java:543)
    at com.sleepycat.je.recovery.RecoveryManager.recover(
        RecoveryManager.java:339)
    at com.sleepycat.je.dbi.EnvironmentImpl.finishInit(
        EnvironmentImpl.java:841)
    at com.sleepycat.je.dbi.DbEnvPool.getEnvironment(DbEnvPool.java:222)
    at com.sleepycat.je.Environment.makeEnvironmentImpl(Environment.java:267)
    at com.sleepycat.je.Environment.init(Environment.java:252)
    at com.sleepycat.je.rep.ReplicatedEnvironment.init(
        ReplicatedEnvironment.java:607)
    at com.sleepycat.je.rep.ReplicatedEnvironment.init(
        ReplicatedEnvironment.java:466)
...
This has been fixed. Without the fix, a workaround for the problem is to remove all the .jdb files from the destination node, before performing the network restore.
[#26311] (7.5.8)
```
code:
```
public InsufficientLogException(Properties properties,
                                    String helperHosts) {
        super(null, EnvironmentFailureReason.INSUFFICIENT_LOG);

        /*
         * Don't initialize the repImpl until it's needed. If we try to do
         * so in step2, we'll be in a loop, trying to recover an environment
         * from  within recovery.
         */
        String vlsnVal =  properties.getProperty(REFRESH_VLSN);
        this.refreshVLSN = new VLSN(Long.parseLong(vlsnVal));     // now use Long
        this.logProviders = new HashSet<>();

        if (helperHosts != null) {
            for (String hostPortPair : helperHosts.split(",")) {
                final String hpp = hostPortPair.trim();
                if (hpp.length() > 0) {
                    LogFileSource source = 
                        new LogFileSource("NoName", // not important
                                          NodeType.ELECTABLE.name(),
                                          HostPortPair.getHostname(hpp),
                                          HostPortPair.getPort(hpp));
                    logProviders.add(source);
                }
            }
        }
        this.props = properties;
    }
```

I've tried to upgrade com.sleepycat-je to 18.3.12, and found this issuse has been resolved and FE started normally.

**Comment by EmmyMiao87** [comment]
>  upgrade com.sleepycat-je to 18.3.12,

Is this a minor version upgrade?

**Comment by acelyc111** [comment]
> > upgrade com.sleepycat-je to 18.3.12,
> 
> Is this a minor version upgrade?
Yes, it's a minor version, in fact it's 7.5.11 (current Doris depends on 7.3.7)

[ref](https://community.oracle.com/tech/developers/discussion/4478434/what-is-the-current-berkeley-db-java-edition-release-is-there-a-public-source-code-repository):
> The current public release of BDB JE is 7.5.11. What you are referring to as 18.3.12 is actually from Oracle NoSQL Database Server. This is a fork of BDB JE and has diverged significantly from the 7.5.11 public version.

**Comment by acelyc111** [comment]
I think the real reason is that we keep a dead observer too long time, the master hold many .bdb files.
