### ISSUE TITLE
rpc failed

### ISSUE THREAD

**Issue by pigdance** [apache/incubator-doris#5599]
1个fe和3个be节点
问题一、通过jdbc批量插入200条记录，经常出现rpc failed，请问是什么原因，怎么改善呢？
问题二、也就千万的数据的明细表，当有数据写入时，查询速度非常慢，而机器负载都不高，怎么改善呢？

**Comment by yangzhg** [comment]
1 是否是使用 事务方式插入？ 如果不是需要先begin transaction   insert 后commit transaction，
2 看下磁盘io 是否 变高了

**Comment by pigdance** [comment]
> 1 是否是使用 事务方式插入？ 如果不是需要先begin transaction insert 后commit transaction，

是基于jdbc默认开启事务方式，一次性导入多行数据,
列如：String sql = INSERT INTO test VALUES (1, 2), (3, 5);
PreparedStatement statement = connection.prepareStatement(sql)) {
statement.execute();

我试了手工提交事务也有类似的rpc 失败
        connection.setAutoCommit(false);
        try (PreparedStatement statement = connection.prepareStatement(sql)) {
            statement.execute();
            connection.commit();
            connection.setAutoCommit(true);
}

**Comment by pigdance** [comment]
2021-04-07 16:51:53,617 WARN (doris-mysql-nio-pool-2441|33463) [Coordinator.exec():519] exec plan fragment failed, errmsg=exec rpc error. backendid: 1281209, code: THRIFT_RPC_ERROR, fragmentId=F00, backend=xxxx:19060
2021-04-07 16:51:53,617 WARN (doris-mysql-nio-pool-2441|33463) [SimpleScheduler.addToBlacklist():141] add black list 1281209
2021-04-07 16:51:53,617 WARN (doris-mysql-nio-pool-2441|33463) [StmtExecutor.handleInsertStmt():868] handle insert stmt fail: insert_7b6470b649f54785-9445751af4234bd2
org.apache.doris.rpc.RpcException: rpc failed, host:ipxxx
        at org.apache.doris.qe.Coordinator.exec(Coordinator.java:528) ~[palo-fe.jar:?]
        at org.apache.doris.qe.StmtExecutor.handleInsertStmt(StmtExecutor.java:809) ~[palo-fe.jar:?]
        at org.apache.doris.qe.StmtExecutor.execute(StmtExecutor.java:289) ~[palo-fe.jar:?]
        at org.apache.doris.qe.ConnectProcessor.handleQuery(ConnectProcessor.java:193) ~[palo-fe.jar:?]
        at org.apache.doris.qe.ConnectProcessor.dispatch(ConnectProcessor.java:325) ~[palo-fe.jar:?]
        at org.apache.doris.qe.ConnectProcessor.processOnce(ConnectProcessor.java:510) ~[palo-fe.jar:?]
        at org.apache.doris.mysql.nio.ReadListener.lambda$handleEvent$0(ReadListener.java:50) ~[palo-fe.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_112]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_112]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_112]
2021-04-07 16:51:53,658 WARN (doris-mysql-nio-pool-2441|33463) [StmtExecutor.execute():343] errors when abort txn
org.apache.doris.transaction.TransactionNotFoundException: errCode = 2, detailMessage = transaction not found
        at org.apache.doris.transaction.DatabaseTransactionMgr.abortTransaction(DatabaseTransactionMgr.java:921) ~[palo-fe.jar:?]
        at org.apache.doris.transaction.GlobalTransactionMgr.abortTransaction(GlobalTransactionMgr.java:207) ~[palo-fe.jar:?]
        at org.apache.doris.transaction.GlobalTransactionMgr.abortTransaction(GlobalTransactionMgr.java:202) ~[palo-fe.jar:?]
        at org.apache.doris.qe.StmtExecutor.execute(StmtExecutor.java:339) ~[palo-fe.jar:?]
        at org.apache.doris.qe.ConnectProcessor.handleQuery(ConnectProcessor.java:193) ~[palo-fe.jar:?]
        at org.apache.doris.qe.ConnectProcessor.dispatch(ConnectProcessor.java:325) ~[palo-fe.jar:?]
        at org.apache.doris.qe.ConnectProcessor.processOnce(ConnectProcessor.java:510) ~[palo-fe.jar:?]
        at org.apache.doris.mysql.nio.ReadListener.lambda$handleEvent$0(ReadListener.java:50) ~[palo-fe.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_112]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_112]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_112]

**Comment by pigdance** [comment]
问题一、问题二 已经解决，原因是FE的内存设置不够大，将之前的4G调到16G问题得到解决
