### ISSUE TITLE
Exception in thread "doris-mysql-nio-pool-0" java.lang.NoSuchMethodError: java.nio.ByteBuffer.limit(I)Ljava/nio/ByteBuffer

### ISSUE THREAD

**Issue by Edon-Du** [apache/incubator-doris#5615]
doris-env-version: 1.3
doris-version:master
jdk:1.8

1. start fe success
2. when I try access through 'mysql -uroot -h127.0.0.1 -P9030' 
3. fe.out output error;
error info:
  Exception in thread "doris-mysql-nio-pool-0" java.lang.NoSuchMethodError: java.nio.ByteBuffer.limit(I)Ljava/nio/ByteBuffer;
          at org.apache.doris.mysql.MysqlChannel.sendOnePacket(MysqlChannel.java:259)
          at org.apache.doris.mysql.MysqlChannel.sendAndFlush(MysqlChannel.java:265)
          at org.apache.doris.mysql.MysqlProto.negotiate(MysqlProto.java:142)
          at org.apache.doris.mysql.nio.AcceptListener.lambda$handleEvent$1(AcceptListener.java:63)
          at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
          at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
          at java.lang.Thread.run(Thread.java:748)

**Comment by Edon-Du** [comment]
doris-env-version: 1.2
doris-version:1.3
jdk:1.8 
deploy success and access mysql success

**Comment by HappenLee** [comment]
doris-env-version: 1.3
update the jdk version to 11
so please try use the openjdk of 11 and try again.

**Comment by Edon-Du** [comment]
> doris-env-version: 1.3
> update the jdk version to 11
> so please try use the openjdk of 11 and try again.

Positive solution
