### ISSUE TITLE
[Bug] StackOverflowError when SHOW ROUTINE LOAD

### ISSUE THREAD

**Issue by morningman** [apache/incubator-doris#5657]
**Describe the bug**
```
2021-04-14 21:40:17,070 WARN (Routine load task scheduler|45) [RoutineLoadTaskScheduler.runAfterCatalogReady():85] Failed to process one round of RoutineLoadTaskScheduler
java.lang.StackOverflowError: null
        at org.apache.doris.load.Load.recursiveRewrite(Load.java:1156) ~[palo-fe.jar:3.4.0]
        at org.apache.doris.load.Load.recursiveRewrite(Load.java:1156) ~[palo-fe.jar:3.4.0]
        at org.apache.doris.load.Load.recursiveRewrite(Load.java:1156) ~[palo-fe.jar:3.4.0]
        at org.apache.doris.load.Load.recursiveRewrite(Load.java:1156) ~[palo-fe.jar:3.4.0]
        at org.apache.doris.load.Load.recursiveRewrite(Load.java:1156) ~[palo-fe.jar:3.4.0]
        at org.apache.doris.load.Load.recursiveRewrite(Load.java:1156) ~[palo-fe.jar:3.4.0]
        at org.apache.doris.load.Load.recursiveRewrite(Load.java:1156) ~[palo-fe.jar:3.4.0]
        at org.apache.doris.load.Load.recursiveRewrite(Load.java:1156) ~[palo-fe.jar:3.4.0]
        at org.apache.doris.load.Load.recursiveRewrite(Load.java:1156) ~[palo-fe.jar:3.4.0]
        at org.apache.doris.load.Load.recursiveRewrite(Load.java:1156) ~[palo-fe.jar:3.4.0]
```

```
2021-04-14 21:41:00,209 WARN (thrift-server-pool-31|213) [ConnectProcessor.proxyExecute():501] Process one query failed because unknown reason:
java.lang.StackOverflowError: null
        at java.lang.String.valueOf(String.java:2994) ~[?:1.8.0_231]
        at java.lang.StringBuilder.append(StringBuilder.java:131) ~[?:1.8.0_231]
        at org.apache.doris.analysis.FunctionCallExpr.toSqlImpl(FunctionCallExpr.java:186) ~[palo-fe.jar:3.4.0]
        at org.apache.doris.analysis.Expr.toSql(Expr.java:866) ~[palo-fe.jar:3.4.0]
        at org.apache.doris.analysis.Expr.childrenToSql(Expr.java:926) ~[palo-fe.jar:3.4.0]
        at org.apache.doris.analysis.FunctionCallExpr.toSqlImpl(FunctionCallExpr.java:193) ~[palo-fe.jar:3.4.0]
        at org.apache.doris.analysis.Expr.toSql(Expr.java:866) ~[palo-fe.jar:3.4.0]
        at org.apache.doris.analysis.Expr.childrenToSql(Expr.java:926) ~[palo-fe.jar:3.4.0]
        at org.apache.doris.analysis.FunctionCallExpr.toSqlImpl(FunctionCallExpr.java:193) ~[palo-fe.jar:3.4.0]
        at org.apache.doris.analysis.Expr.toSql(Expr.java:866) ~[palo-fe.jar:3.4.0]
        at org.apache.doris.analysis.Expr.childrenToSql(Expr.java:926) ~[palo-fe.jar:3.4.0]
        at org.apache.doris.analysis.FunctionCallExpr.toSqlImpl(FunctionCallExpr.java:193) ~[palo-fe.jar:3.4.0]
        at org.apache.doris.analysis.Expr.toSql(Expr.java:866) ~[palo-fe.jar:3.4.0]
        at org.apache.doris.analysis.Expr.childrenToSql(Expr.java:926) ~[palo-fe.jar:3.4.0]
```

**Comment by morningman** [comment]
when writing column mapping like:
(k1, k1=funcA(k1), k2=funcB(k1))

The expected rewriting is:

(k1, k1=funcA(k1), k2=funcB(funcA(k1)))

But when doing the substitution, it may encounter self referencing problem.
When replacing `k1` in `k2=funcB(k1)` with `funcA(k1)`, the `k1` in `funcA(k1)` is also referencing to `funcA(k1)`.
