### ISSUE TITLE
update sql exception

### ISSUE THREAD

**Issue by hf200012** [apache/incubator-doris#5735]
Doris 0.14.7

CREATE TABLE IF NOT EXISTS user001
(
    `user_id` LARGEINT NOT NULL COMMENT "用户id",
    `username` VARCHAR(50) NOT NULL COMMENT "用户昵称",
    `city` VARCHAR(20) COMMENT "用户所在城市"
)
UNIQUE KEY(`user_id`)
 DISTRIBUTED BY HASH(`user_id`) BUCKETS 1;
 
 insert into user001 values (10001,'zhangfeng','西安')
 
 
 update user001 set city='shanghai' where user_id='10001'

Exception 
`java.lang.NullPointerException: null
	at org.apache.doris.load.update.UpdateStmtExecutor.executePlan(UpdateStmtExecutor.java:131) ~[palo-fe.jar:3.4.0]
	at org.apache.doris.load.update.UpdateStmtExecutor.execute(UpdateStmtExecutor.java:99) [palo-fe.jar:3.4.0]
	at org.apache.doris.load.update.UpdateManager.handleUpdate(UpdateManager.java:49) [palo-fe.jar:3.4.0]
	at org.apache.doris.qe.DdlExecutor.execute(DdlExecutor.java:161) [palo-fe.jar:3.4.0]
	at org.apache.doris.qe.StmtExecutor.handleDdlStmt(StmtExecutor.java:1413) [palo-fe.jar:3.4.0]
	at org.apache.doris.qe.StmtExecutor.execute(StmtExecutor.java:379) [palo-fe.jar:3.4.0]
	at org.apache.doris.qe.ConnectProcessor.proxyExecute(ConnectProcessor.java:493) [palo-fe.jar:3.4.0]
	at org.apache.doris.service.FrontendServiceImpl.forward(FrontendServiceImpl.java:659) [palo-fe.jar:3.4.0]
	at org.apache.doris.thrift.FrontendService$Processor$forward.getResult(FrontendService.java:1933) [spark-dpp-1.0.0.jar:1.0.0]
	at org.apache.doris.thrift.FrontendService$Processor$forward.getResult(FrontendService.java:1918) [spark-dpp-1.0.0.jar:1.0.0]
	at org.apache.thrift.ProcessFunction.process(ProcessFunction.java:39) [spark-dpp-1.0.0.jar:1.0.0]
	at org.apache.thrift.TBaseProcessor.process(TBaseProcessor.java:39) [spark-dpp-1.0.0.jar:1.0.0]
	at org.apache.thrift.server.TThreadPoolServer$WorkerProcess.run(TThreadPoolServer.java:286) [spark-dpp-1.0.0.jar:1.0.0]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_261]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_261]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_261]`

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by EmmyMiao87** [comment]
Try to see if there is a problem with executing the update statement directly to the master. 
Or it is still a problem when there is only a non-master.

**Comment by hf200012** [comment]
> Try to see if there is a problem with executing the update statement directly to the master.
> Or it is still a problem when there is only a non-master.
There is no problem connecting fe master to execute this update sql
