### ISSUE TITLE
NPE when replay drop table concurently

### ISSUE THREAD

**Issue by liutang123** [apache/incubator-doris#5992]
**Describe the bug**

**To Reproduce**
Drop same table concurrently.

**Expected behavior**
Table should be droped and no exception.
But, now follower will throw NPE when replay drop table journal.

**Screenshots**
![image](https://user-images.githubusercontent.com/17537020/121124732-f9960300-c857-11eb-982f-8838539c8a78.png)

Follower's LOG:

```2021-06-08 09:06:46,547 INFO (replayer|83) [Catalog.replayJournal():2544] replayed journal id is 1361204889, replay to journal id is 1361204890
2021-06-08 09:06:46,547 INFO (replayer|83) [EditLog.loadJournal():197] Begin to unprotect drop table. db = default_cluster:grocery_doris table = 316815448
2021-06-08 09:06:46,547 INFO (replayer|83) [CatalogRecycleBin.eraseTableWithSameName():279] erase table[316814850] name: app_rt_sc_atnd_rdc_poi_emp_base_hour_date
_temp
2021-06-08 09:06:46,547 INFO (replayer|83) [CatalogRecycleBin.recycleTable():106] recycle table[316815448-app_rt_sc_atnd_rdc_poi_emp_base_hour_date_temp]

2021-06-08 09:06:46,550 INFO (replayer|83) [Catalog.replayJournal():2544] replayed journal id is 1361204890, replay to journal id is 1361204891
2021-06-08 09:06:46,550 INFO (replayer|83) [EditLog.loadJournal():197] Begin to unprotect drop table. db = default_cluster:grocery_doris table = 316815448
2021-06-08 09:06:46,550 ERROR (replayer|83) [EditLog.loadJournal():816] Operation Type 11
java.lang.NullPointerException: null
        at org.apache.doris.catalog.Catalog.replayDropTable(Catalog.java:4542) ~[palo-fe.jar:3.4.0]
        at org.apache.doris.persist.EditLog.loadJournal(EditLog.java:199) [palo-fe.jar:3.4.0]
        at org.apache.doris.catalog.Catalog.replayJournal(Catalog.java:2559) [palo-fe.jar:3.4.0]
        at org.apache.doris.catalog.Catalog$3.runOneCycle(Catalog.java:2343) [palo-fe.jar:3.4.0]
        at org.apache.doris.common.util.Daemon.run(Daemon.java:116) [palo-fe.jar:3.4.0]```

**Comment by liutang123** [comment]
resolved by #5973
