### ISSUE TITLE
[BUG] BE crash at build_side_thread

### ISSUE THREAD

**Issue by crazyleeyang** [apache/incubator-doris#6072]
**Describe the bug**
Occasional breakdown, temporarily unable to reproduce

**Screenshots**
```shell
*** Aborted at 1624005850 (unix time) try "date -d @1624005850" if you are using GNU date ***
PC: @          0x145c083 doris::HashJoinNode::build_side_thread()
*** SIGSEGV (@0x60) received by PID 4263 (TID 0x7f1b25511700) from PID 96; stack trace: ***
    @     0x7f1c861ca670 (unknown)
    @          0x145c083 doris::HashJoinNode::build_side_thread()
    @          0x1a79efd thread_proxy
    @     0x7f1c85f80dc5 start_thread
    @     0x7f1c8628b21d __clone
```

**Desktop (please complete the following information):**
 - Version [0.12.21]

**Comment by caiconghui** [comment]
(gdb) bt
#0  num_available_threads (this=0x7ba70000) at /tmp/jdolap/be/src/runtime/thread_resource_mgr.h:148
#1  release_thread_token (required=false, this=0x7ba70000) at /tmp/jdolap/be/src/runtime/thread_resource_mgr.h:290
#2  doris::HashJoinNode::build_side_thread (this=<optimized out>, state=<optimized out>, status=0x7f9d616e15e0) at /tmp/jdolap/be/src/exec/hash_join_node.cpp:180
#3  0x0000000001a794bd in thread_proxy ()
#4  0x00007f9ed552adc5 in start_thread () from /lib64/libpthread.so.0
#5  0x00007f9ed583521d in clone () from /lib64/libc.so.6
(gdb) f 0
#0  num_available_threads (this=0x7ba70000) at /tmp/jdolap/be/src/runtime/thread_resource_mgr.h:148
148	in /tmp/jdolap/be/src/runtime/thread_resource_mgr.h
(gdb) p
$3 = void
(gdb) p this
$4 = (const doris::ThreadResourceMgr::ResourcePool * const) 0x7ba70000
(gdb) p *this
$5 = {_vptr.ResourcePool = 0x0, _parent = 0x0, _max_quota = 0, _num_reserved_optional_threads = 0, _num_threads = -4294967296, _lock = {m = {__data = {__lock = 0, __count = 0, __owner = 0, __nusers = 0, __kind = -1957707776, __spins = 0, __elision = 0, 
        __list = {__prev = 0x0, __next = 0x278b068 <vtable for doris::TAggregateExpr+16>}}, __size = '\000' <repeats 17 times>, "\300O\213", '\000' <repeats 12 times>, "h\260x\002\000\000\000", __align = 0}}, 
  _thread_available_fn = {<boost::function1<void, doris::ThreadResourceMgr::ResourcePool*>> = {<boost::function_base> = {vtable = 0x6e697861696a7500, functor = {members = {obj_ptr = 0x278b090 <vtable for doris::TBoolLiteral+16>, type = {
              type = 0x278b090 <vtable for doris::TBoolLiteral+16>, const_qualified = false, volatile_qualified = 134}, func_ptr = 0x278b090 <vtable for doris::TBoolLiteral+16>, bound_memfunc_ptr = {
              memfunc_ptr = (void (boost::detail::function::X::*)(boost::detail::function::X * const, int)) 0x278b090 <vtable for doris::TBoolLiteral+16>, this adjustment -8953184999895169536, obj_ptr = 0x278b0b8 <vtable for doris::TCaseExpr+16>}, 
            obj_ref = {obj_ptr = 0x278b090 <vtable for doris::TBoolLiteral+16>, is_const_qualified = false, is_volatile_qualified = 134}}, data = "\220\260x\002\000\000\000\000\000\206中心\270\260x\002\000\000\000"}}, static args = <optimized out>, 
      static arity = <optimized out>}, <No data fields>}}
(gdb) p (*this)._parent
$6 = (doris::ThreadResourceMgr *) 0x0
(gdb) p *((*this)._parent)
Cannot access memory at address 0x0

**Comment by caiconghui** [comment]
the seems strange that thread pool mgr which is parent here now is released
