### ISSUE TITLE
can not fetch partitions

### ISSUE THREAD

**Issue by banjin** [apache/incubator-doris#6137]
java.lang.RuntimeException: can not fetch partitions
        at org.apache.doris.flink.table.DorisDynamicTableSource.getScanRuntimeProvider(DorisDynamicTableSource.java:75)
        at org.apache.flink.table.planner.plan.nodes.common.CommonPhysicalTableSourceScan.createSourceTransformation(CommonPhysicalTableSourceScan.scala:69)
        at org.apache.flink.table.planner.plan.nodes.physical.stream.StreamExecTableSourceScan.translateToPlanInternal(StreamExecTableSourceScan.scala:91)
        at org.apache.flink.table.planner.plan.nodes.physical.stream.StreamExecTableSourceScan.translateToPlanInternal(StreamExecTableSourceScan.scala:44)
        at org.apache.flink.table.planner.plan.nodes.exec.ExecNode$class.translateToPlan(ExecNode.scala:58)
        at org.apache.flink.table.planner.plan.nodes.physical.stream.StreamExecTableSourceScan.translateToPlan(StreamExecTableSourceScan.scala:44)
        at org.apache.flink.table.planner.plan.nodes.physical.stream.StreamExecLegacySink.translateToTransformation(StreamExecLegacySink.scala:158)
        at org.apache.flink.table.planner.plan.nodes.physical.stream.StreamExecLegacySink.translateToPlanInternal(StreamExecLegacySink.scala:106)
        at org.apache.flink.table.planner.plan.nodes.physical.stream.StreamExecLegacySink.translateToPlanInternal(StreamExecLegacySink.scala:48)
        at org.apache.flink.table.planner.plan.nodes.exec.ExecNode$class.translateToPlan(ExecNode.scala:58)
        at org.apache.flink.table.planner.plan.nodes.physical.stream.StreamExecLegacySink.translateToPlan(StreamExecLegacySink.scala:48)
        at org.apache.flink.table.planner.delegation.StreamPlanner$$anonfun$translateToPlan$1.apply(StreamPlanner.scala:67)
        at org.apache.flink.table.planner.delegation.StreamPlanner$$anonfun$translateToPlan$1.apply(StreamPlanner.scala:66)
        at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
        at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
        at scala.collection.Iterator$class.foreach(Iterator.scala:891)
        at scala.collection.AbstractIterator.foreach(Iterator.scala:1334)
        at scala.collection.IterableLike$class.foreach(IterableLike.scala:72)
        at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
        at scala.collection.TraversableLike$class.map(TraversableLike.scala:234)
        at scala.collection.AbstractTraversable.map(Traversable.scala:104)
        at org.apache.flink.table.planner.delegation.StreamPlanner.translateToPlan(StreamPlanner.scala:66)
        at org.apache.flink.table.planner.delegation.PlannerBase.translate(PlannerBase.scala:166)
        at org.apache.flink.table.api.internal.TableEnvironmentImpl.translate(TableEnvironmentImpl.java:1264)
        at org.apache.flink.table.api.internal.TableEnvironmentImpl.executeInternal(TableEnvironmentImpl.java:733)
        at org.apache.flink.table.api.internal.TableEnvironmentImpl.executeOperation(TableEnvironmentImpl.java:1069)
        at org.apache.flink.table.api.internal.TableEnvironmentImpl.executeSql(TableEnvironmentImpl.java:690)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.flink.api.python.shaded.py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
        at org.apache.flink.api.python.shaded.py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
        at org.apache.flink.api.python.shaded.py4j.Gateway.invoke(Gateway.java:282)
        at org.apache.flink.api.python.shaded.py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
        at org.apache.flink.api.python.shaded.py4j.commands.CallCommand.execute(CallCommand.java:79)
        at org.apache.flink.api.python.shaded.py4j.GatewayConnection.run(GatewayConnection.java:238)
        at java.lang.Thread.run(Thread.java:748)

flink 版本 1.11.2

**Comment by banjin** [comment]
当往doris写数据时候，没有报错信息，但是数据也没有写进去
 ```
dorisTableSink = """
    CREATE TABLE flink_doris_sink (
    id INT,
    ip VARCHAR
    )
    WITH (
      'connector' = 'doris',
      'fenodes' = ':8030',
      'table.identifier' = '库.表',
      'username' = '',
      'password' = ''
)

t_env.execute_sql(dorisTableSink)

sql = "insert into flink_doris_sink values (30, '1.2.2.2')"
r = t_env.execute_sql(sql)
r.print()
```

结果:

```
+---------------------------------------------------+
| default_catalog.default_database.flink_doris_sink |
+---------------------------------------------------+
|                                                -1 |
+---------------------------------------------------+
1 row in set
```

数据没有插入成功

**Comment by banjin** [comment]
@JNSimba  -1 代表什么意思？

**Comment by JNSimba** [comment]
> @JNSimba -1 代表什么意思？

The returned number is returned by flink, which means the number of affected rows, -1 means unknown. For details, please refer to https://github.com/apache/flink/blob/488e037285565cc5965c5130ecc92d8a727a4866/flink-table/flink-table-api-java/src/main/java/org/apache/flink/table/api/internal/TableEnvironmentInternal.java#L64

**Comment by JNSimba** [comment]
> 当往doris写数据时候，没有报错信息，但是数据也没有写进去
> 
> ```
> dorisTableSink = """
>    CREATE TABLE flink_doris_sink (
>    id INT,
>    ip VARCHAR
>    )
>    WITH (
>      'connector' = 'doris',
>      'fenodes' = ':8030',
>      'table.identifier' = '库.表',
>      'username' = '',
>      'password' = ''
> )
> 
> t_env.execute_sql(dorisTableSink)
> 
> sql = "insert into flink_doris_sink values (30, '1.2.2.2')"
> r = t_env.execute_sql(sql)
> r.print()
> ```
> 
> 结果:
> 
> ```
> +---------------------------------------------------+
> | default_catalog.default_database.flink_doris_sink |
> +---------------------------------------------------+
> |                                                -1 |
> +---------------------------------------------------+
> 1 row in set
> ```
> 
> 数据没有插入成功

Take a look at the complete log information, is it an error during streamload?

**Comment by banjin** [comment]
org.apache.flink.client.program.ProgramAbortException
	at org.apache.flink.client.python.PythonDriver.main(PythonDriver.java:111)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.flink.client.program.PackagedProgram.callMainMethod(PackagedProgram.java:288)
	at org.apache.flink.client.program.PackagedProgram.invokeInteractiveModeForExecution(PackagedProgram.java:198)
	at org.apache.flink.client.ClientUtils.executeProgram(ClientUtils.java:149)
	at org.apache.flink.client.cli.CliFrontend.executeProgram(CliFrontend.java:699)
	at org.apache.flink.client.cli.CliFrontend.run(CliFrontend.java:232)
	at org.apache.flink.client.cli.CliFrontend.parseParameters(CliFrontend.java:916)
	at org.apache.flink.client.cli.CliFrontend.lambda$main$10(CliFrontend.java:992)
	at org.apache.flink.runtime.security.contexts.NoOpSecurityContext.runSecured(NoOpSecurityContext.java:30)
	at org.apache.flink.client.cli.CliFrontend.main(CliFrontend.java:992)

当我执行 flink run -py temp.py 时候报了这个错误

**Comment by banjin** [comment]
org.apache.flink.client.program.ProgramAbortException
	at org.apache.flink.client.python.PythonDriver.main(PythonDriver.java:111)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.flink.client.program.PackagedProgram.callMainMethod(PackagedProgram.java:288)
	at org.apache.flink.client.program.PackagedProgram.invokeInteractiveModeForExecution(PackagedProgram.java:198)
	at org.apache.flink.client.ClientUtils.executeProgram(ClientUtils.java:149)
	at org.apache.flink.client.cli.CliFrontend.executeProgram(CliFrontend.java:699)
	at org.apache.flink.client.cli.CliFrontend.run(CliFrontend.java:232)
	at org.apache.flink.client.cli.CliFrontend.parseParameters(CliFrontend.java:916)
	at org.apache.flink.client.cli.CliFrontend.lambda$main$10(CliFrontend.java:992)
	at org.apache.flink.runtime.security.contexts.NoOpSecurityContext.runSecured(NoOpSecurityContext.java:30)
	at org.apache.flink.client.cli.CliFrontend.main(CliFrontend.java:992)

当我执行 flink run -py temp.py 时候报了这个错误


但是当我执行python3 temp.py时候没有报错信息，返回上面的值 -1

**Comment by banjin** [comment]
我已经找到为-1的原因  ，但是现在在执行任务时候有以下问题![image](https://user-images.githubusercontent.com/15867545/124412335-d724d600-dd80-11eb-8bdb-b8d8a580dd6c.png)

**Comment by JNSimba** [comment]
![image](https://user-images.githubusercontent.com/7951521/124423914-a8b2f500-dd98-11eb-943d-6ff2f7d5c342.png)

Streamload has error，look at this  complete line

**Comment by banjin** [comment]
好的，已经找到原因了，由于网络环境导致，1.11版本可以正常写入，非常感谢

@JNSimba  

希望1.13版本能够尽早更新，祝好
