### ISSUE TITLE
Could not initialize class org.apache.doris.rpc.BackendServiceProxy

### ISSUE THREAD

**Issue by maydayd2** [apache/incubator-doris#6178]
java.lang.NoClassDefFoundError: Could not initialize class org.apache.doris.rpc.BackendServiceProxy
        at org.apache.doris.qe.Coordinator$BackendExecState.execRemoteFragmentAsync(Coordinator.java:1823) ~[palo-fe.jar:3.4.0]
        at org.apache.doris.qe.Coordinator.sendFragment(Coordinator.java:509) ~[palo-fe.jar:3.4.0]
        at org.apache.doris.qe.Coordinator.exec(Coordinator.java:447) ~[palo-fe.jar:3.4.0]
        at org.apache.doris.qe.StmtExecutor.handleQueryStmt(StmtExecutor.java:763) ~[palo-fe.jar:3.4.0]
        at org.apache.doris.qe.StmtExecutor.execute(StmtExecutor.java:298) ~[palo-fe.jar:3.4.0]
        at org.apache.doris.qe.StmtExecutor.execute(StmtExecutor.java:243) ~[palo-fe.jar:3.4.0]
        at org.apache.doris.qe.ConnectProcessor.handleQuery(ConnectProcessor.java:199) ~[palo-fe.jar:3.4.0]
        at org.apache.doris.qe.ConnectProcessor.dispatch(ConnectProcessor.java:337) ~[palo-fe.jar:3.4.0]
        at org.apache.doris.qe.ConnectProcessor.processOnce(ConnectProcessor.java:535) ~[palo-fe.jar:3.4.0]
        at org.apache.doris.mysql.nio.ReadListener.lambda$handleEvent$0(ReadListener.java:50) ~[palo-fe.jar:3.4.0]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_292]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_292]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_292]

**Comment by maydayd2** [comment]
use orcale jdk
