### ISSUE TITLE
[Bug] BE crash when query union and join

### ISSUE THREAD

**Issue by morningman** [apache/incubator-doris#6327]
**Describe the bug**
```
SELECT a.x FROM
(SELECT '01' x UNION all SELECT '02') a
INNER JOIN
(SELECT '01' x UNION all SELECT '02') b
```

BE crash:

```
*** Aborted at 1627349345 (unix time) try "date -d @1627349345" if you are using GNU date ***
PC: @          0x1566534 doris::Tuple::materialize_exprs<>()
*** SIGSEGV (@0x0) received by PID 73779 (TID 0x7f3007765700) from PID 0; stack trace: ***
    @          0x20c7d52 google::(anonymous namespace)::FailureSignalHandler()
    @     0x7f306926d1d0 (unknown)
    @          0x1566534 doris::Tuple::materialize_exprs<>()
    @          0x1a9818b doris::UnionNode::materialize_exprs()
    @          0x1a9622c doris::UnionNode::get_next_const()
    @          0x1a96bc2 doris::UnionNode::get_next()
    @          0x1559293 doris::PlanFragmentExecutor::get_next_internal()
    @          0x15599e9 doris::PlanFragmentExecutor::open_internal()
    @          0x155e1cf doris::PlanFragmentExecutor::open()
    @          0x14d3e1e doris::FragmentExecState::execute()
    @          0x14d7486 doris::FragmentMgr::_exec_actual()
    @          0x14dec9b std::_Function_handler<>::_M_invoke()
    @          0x1649866 doris::ThreadPool::dispatch_thread()
    @          0x1643ca4 doris::Thread::supervise_thread()
    @     0x7f3069262f84 start_thread
    @     0x7f3069052ddf __GI___clone
```

**Version**
trunk

**Comment by xinyiZzz** [comment]
When the child of the Union on the right side of the join is not a constant, it is ScanNode:
```
SELECT a.x 
FROM (SELECT '01' x) a 
INNER JOIN 
(SELECT C_CUSTKEY from CUSTOMER 
UNION all 
SELECT C_CUSTKEY from CUSTOMER) b;
```

The `Preconditions.checkState` in the FE will report an error
```
java.lang.IllegalStateException: null
        at com.google.common.base.Preconditions.checkState(Preconditions.java:492) ~[spark-dpp-1.0.0.jar:1.0.0]
        at org.apache.doris.planner.DataPartition.<init>(DataPartition.java:62) ~[palo-fe.jar:3.4.0]
        at org.apache.doris.planner.DistributedPlanner.createSetOperationNodeFragment(DistributedPlanner.java:815) ~[palo-fe.jar:3.4.0]
        at org.apache.doris.planner.DistributedPlanner.createPlanFragments(DistributedPlanner.java:213) ~[palo-fe.jar:3.4.0]
        at org.apache.doris.planner.DistributedPlanner.createPlanFragments(DistributedPlanner.java:196) ~[palo-fe.jar:3.4.0]
        at org.apache.doris.planner.DistributedPlanner.createPlanFragments(DistributedPlanner.java:104) ~[palo-fe.jar:3.4.0]
        at org.apache.doris.planner.Planner.createPlanFragments(Planner.java:214) ~[palo-fe.jar:3.4.0]
        at org.apache.doris.planner.Planner.plan(Planner.java:84) ~[palo-fe.jar:3.4.0]
        at org.apache.doris.qe.StmtExecutor.analyzeAndGenerateQueryPlan(StmtExecutor.java:630) ~[palo-fe.jar:3.4.0]
        at org.apache.doris.qe.StmtExecutor.analyze(StmtExecutor.java:514) ~[palo-fe.jar:3.4.0]
        at org.apache.doris.qe.StmtExecutor.execute(StmtExecutor.java:302) ~[palo-fe.jar:3.4.0]
        at org.apache.doris.qe.StmtExecutor.execute(StmtExecutor.java:275) ~[palo-fe.jar:3.4.0]
        at org.apache.doris.qe.ConnectProcessor.handleQuery(ConnectProcessor.java:206) ~[palo-fe.jar:3.4.0]
        at org.apache.doris.qe.ConnectProcessor.dispatch(ConnectProcessor.java:344) ~[palo-fe.jar:3.4.0]
        at org.apache.doris.qe.ConnectProcessor.processOnce(ConnectProcessor.java:545) ~[palo-fe.jar:3.4.0]
        at org.apache.doris.mysql.nio.ReadListener.lambda$handleEvent$0(ReadListener.java:50) ~[palo-fe.jar:3.4.0]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_252]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_252]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_252]
```
