### ISSUE TITLE
doris flink connector do not support flink 1.13 [Bug] 

### ISSUE THREAD

**Issue by xhmz** [apache/incubator-doris#6624]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-doris/issues?q=is%3Aissue) and found no similar issues.

### Version

1.13

### What's Wrong?

org.apache.flink.table.data.binary.BinaryRowData cannot be cast to org.apache.flink.table.data.GenericRowData
	at org.apache.doris.flink.table.DorisDynamicOutputFormat.addBatch(DorisDynamicOutputFormat.java:142)
	at org.apache.doris.flink.table.DorisDynamicOutputFormat.writeRecord(DorisDynamicOutputFormat.java:133)
	at org.apache.doris.flink.table.DorisDynamicOutputFormat.writeRecord(DorisDynamicOutputFormat.java:45)
	at org.apache.flink.streaming.api.functions.sink.OutputFormatSinkFunction.invoke(OutputFormatSinkFunction.java:87)
	at org.apache.flink.streaming.api.functions.sink.SinkFunction.invoke(SinkFunction.java:49)
	at org.apache.flink.table.runtime.operators.sink.SinkOperator.processElement(SinkOperator.java:65)
	at org.apache.flink.streaming.runtime.tasks.OneInputStreamTask$StreamTaskNetworkOutput.emitRecord(OneInputStreamTask.java:205)
	at org.apache.flink.streaming.runtime.io.AbstractStreamTaskNetworkInput.processElement(AbstractStreamTaskNetworkInput.java:134)
	at org.apache.flink.streaming.runtime.io.AbstractStreamTaskNetworkInput.emitNext(AbstractStreamTaskNetworkInput.java:105)
	at org.apache.flink.streaming.runtime.io.StreamOneInputProcessor.processInput(StreamOneInputProcessor.java:66)
	at org.apache.flink.streaming.runtime.tasks.StreamTask.processInput(StreamTask.java:423)
	at org.apache.flink.streaming.runtime.tasks.mailbox.MailboxProcessor.runMailboxLoop(MailboxProcessor.java:204)
	at org.apache.flink.streaming.runtime.tasks.StreamTask.runMailboxLoop(StreamTask.java:681)
	at org.apache.flink.streaming.runtime.tasks.StreamTask.executeInvoke(StreamTask.java:636)
	at org.apache.flink.streaming.runtime.tasks.StreamTask.runWithCleanUpOnFail(StreamTask.java:647)
	at org.apache.flink.streaming.runtime.tasks.StreamTask.invoke(StreamTask.java:620)
	at org.apache.flink.runtime.taskmanager.Task.doRun(Task.java:779)
	at org.apache.flink.runtime.taskmanager.Task.run(Task.java:566)
	at java.lang.Thread.run(Thread.java:748)

### What You Expected?

no error

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by JNSimba** [comment]
Well, It's a bug, I am dealing with this problem , In what situation are you get this exception ? can you show your flinksql ?

**Comment by xhmz** [comment]
--CREATE TABLE random_source (
 --   id INT,
 --   f_random_str VARCHAR
 -- ) WITH ( 
 -- 'connector' = 'datagen', 
 -- 'rows-per-second'='2',               -- 每秒产生的数据条数
 -- 'fields.id.kind'='sequence',   -- 有界序列（结束后自动停止输出）
 -- 'fields.id.start'='1',         -- 序列的起始值
 -- 'fields.id.end'='10000',       -- 序列的终止值
 -- 'fields.f_random_str.length'='100'      -- 随机字符串的长度
--);
CREATE TABLE flink_doris_source (
    id INT,
    f_random_str VARCHAR
    ) 
    WITH (
      'connector' = 'doris',                    -- 固定值 'doris'
      'fenodes' = 'xxx',          -- Doris FE http 地址
      'table.identifier' = 'test.xxx',  -- Doris 表名 格式：db1.tbl1
      'username' = 'xxx',                      -- 访问Doris的用户名
      'password' = 'xxx'                 -- 访问Doris的密码
      --'sink.batch.size' = '500',                -- 单次写BE的最大行数
     -- 'sink.batch.interval' = '1s'              -- flush 间隔时间，超过该时间后异步线程将 缓存中数据写入BE。 默认值为1秒，支持时间单位ms、s、min、h和d。设置为0表示关闭定期写入。
);
INSERT INTO flink_doris_source select id, f_random_str from source;

> can you show your flinksql ?

**Comment by xhmz** [comment]
doris sink format， not use GenericRowData. use RowData::FieldGetter， fixed it。

**Comment by xhmz** [comment]
https://github.com/apache/incubator-doris/pull/6655

**Comment by xhmz** [comment]
set pipeline.operator-chaining = false  
this param cause the bug

**Comment by JNSimba** [comment]
> doris sink format， not use GenericRowData. use RowData::FieldGetter， fixed it。

great，use RowData::FieldGetter is worked

**Comment by JNSimba** [comment]
> set pipeline.operator-chaining = false
> this param cause the bug

I try to set **disableOperatorChaining** , this problem still occurs . such as flinksql has **limit xxxx**

**Comment by xhmz** [comment]
yes， if you disableOperatorChaining， RowDataSerializer will Serialize RowData to BinaryRowData

**Comment by xhmz** [comment]
> > set pipeline.operator-chaining = false
> > this param cause the bug
> 
> I try to set **disableOperatorChaining** , this problem still occurs . such as flinksql has **limit xxxx** .
> and this parameter may be reduces flink performance

我的意思是设置这个参数会 导致这个错误～
