### ISSUE TITLE
[Bug]  Broker Load  从 hdfs3.3.1 导入数据到 doris 中,  日志提示Could not initialize class org.apache.hadoop.util.StringUtils 

### ISSUE THREAD

**Issue by aubdiy** [apache/incubator-doris#7983]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-doris/issues?q=is%3Aissue) and found no similar issues.

### Version

0.15.0

### What's Wrong?

Broker Load  从 hdfs3.3.1 导入数据到 doris 中,  日志提示
```
receive a ping request, request detail: TBrokerPingBrokerRequest(version:VERSION_ONE, clientId:172.31.3.146)
[INFO ] 2022-02-08 08:07:10,947 method:org.apache.doris.broker.hdfs.HDFSBrokerServiceImpl.listPath(HDFSBrokerServiceImpl.java:67)
received a list path request, request detail: TBrokerListPathRequest(version:VERSION_ONE, path:hdfs://test.internal:8020/tmp/data.csv, isRecursive:false, properties:{_DORIS_STORAGE_TYPE_=BROKER})
[INFO ] 2022-02-08 08:07:10,948 method:org.apache.doris.broker.hdfs.FileSystemManager.getDistributedFileSystem(FileSystemManager.java:244)
create file system for new path: hdfs://test.internal:8020/tmp/data.csv
Exception in thread "pool-2-thread-13" java.lang.NoClassDefFoundError: Could not initialize class org.apache.hadoop.util.StringUtils
    at org.apache.hadoop.conf.Configuration.getBoolean(Configuration.java:1437)
    at org.apache.hadoop.fs.FileSystem.get(FileSystem.java:369)
    at org.apache.doris.broker.hdfs.FileSystemManager.getDistributedFileSystem(FileSystemManager.java:360)
    at org.apache.doris.broker.hdfs.FileSystemManager.getFileSystem(FileSystemManager.java:152)
    at org.apache.doris.broker.hdfs.FileSystemManager.listPath(FileSystemManager.java:427)
    at org.apache.doris.broker.hdfs.HDFSBrokerServiceImpl.listPath(HDFSBrokerServiceImpl.java:74)
    at org.apache.doris.thrift.TPaloBrokerService$Processor$listPath.getResult(TPaloBrokerService.java:815)
    at org.apache.doris.thrift.TPaloBrokerService$Processor$listPath.getResult(TPaloBrokerService.java:795)
    at org.apache.thrift.ProcessFunction.process(ProcessFunction.java:38)
    at org.apache.thrift.TBaseProcessor.process(TBaseProcessor.java:38)
    at org.apache.thrift.server.TThreadPoolServer$WorkerProcess.run(TThreadPoolServer.java:313)
    at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
    at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
    at java.base/java.lang.Thread.run(Thread.java:834)
[INFO ] 2022-02-08 08:07:10,963 method:org.apache.doris.broker.hdfs.HDFSBrokerServiceImpl.listPath(HDFSBrokerServiceImpl.java:67)
received a list path request, request detail: TBrokerListPathRequest(version:VERSION_ONE, path:hdfs://test.internal:8020/tmp/data.csv, isRecursive:false, properties:{_DORIS_STORAGE_TYPE_=BROKER})
```

### What You Expected?

希望能够正常导入

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by aubdiy** [comment]
问题已经修复.
修复过程:
1.  进入 fs_brokers/apache_hdfs_broker
2. 执行编译, 编译成功后将 `output/apache_hdfs_broker/lib/apache_hdfs_broker.jar` 保留代用,  然后删除掉 `output` 目录 
3. 修改 pom.xml 文件中 hadoop 相关依赖,  将 2.7.3 改为 3.3.1
4. 修改 pom.xml 文件, 删除 hadoop-hdfs 包, 增加  hadoop-hdfs-client 包(3.3.1) 版本
5. 修改 pom.xml 文件中 hadoop-aws 相关依赖,  将 2.7.3 改为 3.3.1
6. 修改 `fs_brokers/apache_hdfs_broker/src/main/java/org/apache/doris/broker/hdfs/FileSystemManager.java:[636,15]` 代码, 将 ' } catch (IOException e) {'   替换为 ' } catch (Exception e) {' , 否则编译会提示 
  ```
  [ERROR] /root/incubator-doris-DORIS-0.15.0-release/apache-doris-0.15.0-incubating-src/fs_brokers/apache_hdfs_broker/src/main/java/org/apache/doris/broker/hdfs/FileSystemManager.java:[636,15] exception java.io.IOException is never thrown in body of corresponding try statement
 ```
7. 执行编译 sh build.sh 
8. 编译成功后,  将第2 步中的  `apache_hdfs_broker.jar` 覆盖  `output/apache_hdfs_broker/lib/apache_hdfs_broker.jar` 
9. 重新部署 hdf_broker ,   可以正常导入
