### ISSUE TITLE
[Bug] Fix segmentation fault at unalign address cast to int128

### ISSUE THREAD

**Issue by BiteTheDDDDt** [apache/incubator-doris#8020]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-doris/issues?q=is%3Aissue) and found no similar issues.

### Version

master

### What's Wrong?

Fix segmentation fault at unalign address cast to int128

### What You Expected?

fix it

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by BiteTheDDDDt** [comment]
backtrace infomation:
```cpp
Thread 1 "row_cursor_test" received signal SIGSEGV, Segmentation fault.
0x0000000000b44ed9 in doris::TestRowCursor_AggregateWithoutNull_Test::TestBody (this=<optimized out>) at doris/core/be/test/olap/row_cursor_test.cpp:501
501	    int128_t agg_value = *reinterpret_cast<int128_t*>(row.cell_ptr(2));
Execute debugger commands using "-exec <command>", for example "-exec info registers" will list registers in use (when GDB is the debugger)
-exec bt
#0  0x0000000000b44ed9 in doris::TestRowCursor_AggregateWithoutNull_Test::TestBody (this=<optimized out>) at doris/core/be/test/olap/row_cursor_test.cpp:501
#1  0x0000000001df8bd3 in void testing::internal::HandleSehExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) ()
#2  0x0000000001df1637 in void testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) ()
#3  0x0000000001dc6682 in testing::Test::Run() ()
#4  0x0000000001dc70a6 in testing::TestInfo::Run() ()
#5  0x0000000001dc7966 in testing::TestSuite::Run() ()
#6  0x0000000001dd7026 in testing::internal::UnitTestImpl::RunAllTests() ()
#7  0x0000000001df9ab0 in bool testing::internal::HandleSehExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) ()
#8  0x0000000001df262d in bool testing::internal::HandleExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) ()
#9  0x0000000001dd581b in testing::UnitTest::Run() ()
#10 0x0000000000b47a81 in RUN_ALL_TESTS () at doris/core/thirdparty/installed/include/gtest/gtest.h:2490
#11 main (argc=1, argv=<optimized out>) at doris/core/be/test/olap/row_cursor_test.cpp:578
```
