### ISSUE TITLE
FOLLOWER FE tablet meta is wrong

### ISSUE THREAD

**Issue by kangkaisen** [apache/incubator-doris#812]
**Describe the bug**
for a same query
```
SELECT * FROM  table WHERE deliver_date = '2019-03-16' AND  source_system='QCS' limit 1;
```
The Master FE could run successfully.
but the FOLLOWER or OBSERVER FE will get the following error:
```
 Failed to get scan range, no replica!
```
**Even if I restart the FOLLOWER and OBSERVER FE, I still get the same error.**

I check **the image size for all FE is the same.**

I debug the OBSERVER FE,
The right tablet meta is following:
![image](https://user-images.githubusercontent.com/9894906/54922701-aae44300-4f43-11e9-9363-cf3596e94024.png)

The wrong tablet meta is following:
**The replica version meta is wrong!**
![image](https://user-images.githubusercontent.com/9894906/54922742-c3545d80-4f43-11e9-8321-77ffe60bda0c.png)

**Comment by kangkaisen** [comment]
I checked the md5 for image file in all FE, which md5 value are the same.

**Comment by kangkaisen** [comment]
The master FE has changed automatically. But the strange things is the new master FE still could query successfully and other FE will query failed.

**Comment by kangkaisen** [comment]
It's seems the `loadImage` is different for master FE and FOLLOWER FE. But I looked the code in `Catalog.loadImage`, I didn't find the different logic for master FE and FOLLOWER FE.

**Comment by kangkaisen** [comment]
**The root reason is BE meta is right but FE persistent meta is wrong.**
**The Master FE meta is right  because `ReportHandler.sync` fix the replica version, But the update not persistent.**

```
2019-03-25 23:00:52,766 INFO 72 [Catalog.transferToMaster():963] finish replay in 0 msec

log/fe.log.20190325:2019-03-25 23:02:03,717 INFO 89 [ReportHandler.sync():302] before sync tablets in db[55506441]. report num: 2808. backend[66211303]
log/fe.log.20190325:2019-03-25 23:02:03,725 INFO 89 [ReportHandler.sync():383] sync 2808 tablets in db[55506441]. backend[66211303]
log/fe.log.20190325:2019-03-25 23:02:09,319 INFO 89 [ReportHandler.sync():302] before sync tablets in db[55506441]. report num: 2833. backend[54910375]
log/fe.log.20190325:2019-03-25 23:02:09,329 INFO 89 [ReportHandler.sync():383] sync 2833 tablets in db[55506441]. backend[54910375]
log/fe.log.20190325:2019-03-25 23:02:10,470 INFO 89 [ReportHandler.sync():302] before sync tablets in db[55506441]. report num: 2810. backend[54910376]
log/fe.log.20190325:2019-03-25 23:02:10,479 INFO 89 [ReportHandler.sync():383] sync 2810 tablets in db[55506441]. backend[54910376]
log/fe.log.20190325:2019-03-25 23:02:15,561 INFO 89 [ReportHandler.sync():302] before sync tablets in db[55506441]. report num: 2812. backend[54908822]
log/fe.log.20190325:2019-03-25 23:02:15,570 INFO 89 [ReportHandler.sync():383] sync 2812 tablets in db[55506441]. backend[54908822]
log/fe.log.20190325:2019-03-25 23:02:22,061 INFO 89 [ReportHandler.sync():302] before sync tablets in db[55506441]. report num: 2756. backend[66211305]
log/fe.log.20190325:2019-03-25 23:02:22,069 INFO 89 [ReportHandler.sync():383] sync 2756 tablets in db[55506441]. backend[66211305]
log/fe.log.20190325:2019-03-25 23:02:23,413 INFO 89 [ReportHandler.sync():302] before sync tablets in db[55506441]. report num: 2804. backend[66211304]
log/fe.log.20190325:2019-03-25 23:02:23,423 INFO 89 [ReportHandler.sync():383] sync 2804 tablets in db[55506441]. backend[66211304]



2019-03-25 23:02:23,422 INFO 89 [Replica.updateReplicaInfo():195] current version 16177 is larger than last failed version 8860 ,
last failed version hash 3367386833966679899, maybe a fatal error or be report version, print a stack here
java.lang.Exception
        at org.apache.doris.catalog.Replica.updateReplicaInfo(Replica.java:197) [palo-fe.jar:?]
        at org.apache.doris.catalog.Replica.updateInfo(Replica.java:160) [palo-fe.jar:?]
        at org.apache.doris.master.ReportHandler.sync(ReportHandler.java:371) [palo-fe.jar:?]
        at org.apache.doris.master.ReportHandler.tabletReport(ReportHandler.java:210) [palo-fe.jar:?]
        at org.apache.doris.master.ReportHandler.access$300(ReportHandler.java:79) [palo-fe.jar:?]
        at org.apache.doris.master.ReportHandler$ReportTask.exec(ReportHandler.java:166) [palo-fe.jar:?]
        at org.apache.doris.master.ReportHandler.runOneCycle(ReportHandler.java:764) [palo-fe.jar:?]
        at org.apache.doris.common.util.Daemon.run(Daemon.java:96) [palo-fe.jar:?]
```

**Comment by kangkaisen** [comment]
I think https://github.com/apache/incubator-doris/pull/600 has fixed this issue.

**Comment by kangkaisen** [comment]
Our prod FE tablet meta has been fixed and the query for all FE could run successfully.

```
    2019-03-26 12:32:26,753 INFO 84 [Catalog.unprotectUpdateReplica():4182] replay update a replica table id: 55764787 partition id: 8
2566774 index id: 55764787 index id: 55764787 tablet id: 82566795 backend id: 66211303 replica id: 82566796 version: 16177 version
 hash: 4385724978675277530 data size: 38809696 row count: 1005342 last failed version: -1 last failed version hash: 0 last success
 version: 16177 last success version hash: 4385724978675277530
```

**Comment by kangkaisen** [comment]
If you use old version Doris, you could directly cherry-pick this patch.
[mete-sync-persistent-bug.patch.txt](https://github.com/apache/incubator-doris/files/3006524/mete-sync-persistent-bug.patch.txt)
