### ISSUE TITLE
[Bug] NullPointer in FunctionCallExpr::paramsToSql

### ISSUE THREAD

**Issue by xinyiZzz** [apache/incubator-doris#8844]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-doris/issues?q=is%3Aissue) and found no similar issues.

### Version

trunk

### What's Wrong?

Introduced in #8485

2022-04-04 06:11:17,073 WARN (doris-mysql-nio-pool-0|121) [StmtExecutor.analyze():583] Analyze failed. stmt[4, 9054ab31b9d14e4e-b6e655cc07ac7365]
java.lang.NullPointerException: null
        at org.apache.doris.analysis.FunctionCallExpr.paramsToSql(FunctionCallExpr.java:249) ~[palo-fe.jar:1.0-SNAPSHOT]
        at org.apache.doris.analysis.FunctionCallExpr.toSqlImpl(FunctionCallExpr.java:285) ~[palo-fe.jar:1.0-SNAPSHOT]
        at org.apache.doris.analysis.Expr.toSql(Expr.java:871) ~[palo-fe.jar:1.0-SNAPSHOT]
        at org.apache.doris.analysis.Expr.toColumnLabel(Expr.java:888) ~[palo-fe.jar:1.0-SNAPSHOT]
        at org.apache.doris.analysis.SelectListItem.toColumnLabel(SelectListItem.java:110) ~[palo-fe.jar:1.0-SNAPSHOT]
        at org.apache.doris.analysis.SelectStmt.analyze(SelectStmt.java:427) ~[palo-fe.jar:1.0-SNAPSHOT]
        at org.apache.doris.qe.StmtExecutor.analyzeAndGenerateQueryPlan(StmtExecutor.java:636) ~[palo-fe.jar:1.0-SNAPSHOT]
        at org.apache.doris.qe.StmtExecutor.analyze(StmtExecutor.java:571) ~[palo-fe.jar:1.0-SNAPSHOT]
        at org.apache.doris.qe.StmtExecutor.execute(StmtExecutor.java:327) ~[palo-fe.jar:1.0-SNAPSHOT]
        at org.apache.doris.qe.StmtExecutor.execute(StmtExecutor.java:300) ~[palo-fe.jar:1.0-SNAPSHOT]
        at org.apache.doris.qe.ConnectProcessor.handleQuery(ConnectProcessor.java:212) ~[palo-fe.jar:1.0-SNAPSHOT]
        at org.apache.doris.qe.ConnectProcessor.dispatch(ConnectProcessor.java:349) ~[palo-fe.jar:1.0-SNAPSHOT]
        at org.apache.doris.qe.ConnectProcessor.processOnce(ConnectProcessor.java:538) ~[palo-fe.jar:1.0-SNAPSHOT]
        at org.apache.doris.mysql.nio.ReadListener.lambda$handleEvent$0(ReadListener.java:50) ~[palo-fe.jar:1.0-SNAPSHOT]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[?:?]
        at java.lang.Thread.run(Thread.java:834) ~[?:?]

### Recurrent
```
select count(*) from t8030_le_test_set_time_zone_stream_load_FROM_UNIXTIME_tb;

CREATE TABLE d505c_le_test_set_time_zone_stream_load_FROM_UNIXTIME_db.t8030_le_test_set_time_zone_stream_load_FROM_UNIXTIME_tb ( k1 tinyint NOT NULL, k2 smallint NOT NULL, k3 int NOT NULL, k4 bigint NOT NULL, k5 decimal(9, 3) NOT NULL, k6 char(5) NOT NULL, k10 date NOT NULL, k11 datetime NOT NULL, k7 varchar(20) NOT NULL, k8 double max NOT NULL, k9 float sum NOT NULL ) AGGREGATE KEY(k1,k2,k3,k4,k5,k6,k10,k11,k7) PARTITION BY RANGE(k2) ( PARTITION partition_a VALUES LESS THAN MAXVALUE ) DISTRIBUTED BY HASH(k1, k2, k5) BUCKETS 3;
```

### What You Expected?

win

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by xinyiZzz** [comment]
cc @dataroaring

**Comment by xinyiZzz** [comment]
#8838
