### ISSUE TITLE
[Enhancement] [regression-test] when suite with more than 2 input will error

### ISSUE THREAD

**Issue by zhangy5** [apache/incubator-doris#9093]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-doris/issues?q=is%3Aissue) and found no similar issues.

### Description

when test_accout.groovy is:  suite("test_account", "account", "dd")
suite meet errors like: 

2022-04-18 12:13:07.143 ERROR [pool-2-thread-1] (ScriptContext.groovy:157) - Fatal: run SuiteScript in /root/doris-test/regression-test/suites/account/test_account.groovy failed
groovy.lang.MissingMethodException: No signature of method: test_account.suite() is applicable for argument types: (String, String, String, test_account$_run_closure1) values: [test_account, account, dd, test_account$_run_closure1@4925bbad]
Possible solutions: suite(java.lang.String, java.lang.String, groovy.lang.Closure), suite(java.lang.String, groovy.lang.Closure), wait(), run(), run(), dump()
	at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.unwrap(ScriptBytecodeAdapter.java:70)
	at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.callCurrent(PogoMetaClassSite.java:80)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:51)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:171)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:212)
	at test_account.run(test_account.groovy:17)
	at org.apache.doris.regression.RegressionTest$_runScript_closure4.doCall(RegressionTest.groovy:126)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:107)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323)
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:263)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1035)
	at groovy.lang.Closure.call(Closure.java:412)
	at org.codehaus.groovy.runtime.ConvertedClosure.invokeCustom(ConvertedClosure.java:50)
	at org.codehaus.groovy.runtime.ConversionHandler.invoke(ConversionHandler.java:110)
	at com.sun.proxy.$Proxy15.apply(Unknown Source)
	at org.apache.doris.regression.suite.ScriptContext$_start_closure3.doCall(ScriptContext.groovy:152)
	at org.apache.doris.regression.suite.ScriptContext$_start_closure3.call(ScriptContext.groovy)
	at org.codehaus.groovy.runtime.IOGroovyMethods.withCloseable(IOGroovyMethods.java:1607)
	at org.apache.doris.regression.suite.ScriptContext.start(ScriptContext.groovy:150)
	at org.apache.doris.regression.RegressionTest.runScript(RegressionTest.groovy:122)
	at org.apache.doris.regression.RegressionTest$_runScripts_closure5$_closure13.doCall(RegressionTest.groovy:146)
	at org.apache.doris.regression.RegressionTest$_runScripts_closure5$_closure13.call(RegressionTest.groovy)
	at groovy.lang.Closure.run(Closure.java:493)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829

I prefer to use suite to filter case. A suite maybe has some tags like:
p0/p1/p2
with_hdfs
with_mysql
with_kafka
multi_be
single_be
...

So, the test can run in different situations and suite may have tags more than 2.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by EmmyMiao87** [comment]
This is not a bug.
If you want to set multi group in one suite, it will be like ```suite("suitename", "group1, group2")```
