### ISSUE TITLE
[Bug] `Status::ConstructErrorStatus` core dump

### ISSUE THREAD

**Issue by xinyiZzz** [apache/incubator-doris#9218]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-doris/issues?q=is%3Aissue) and found no similar issues.

### Version

trunk

### What's Wrong?

0  0x000055bf2e801afb in backtrace_free_locked ()
#1  0x000055bf2e801dcb in backtrace_free ()
#2  0x000055bf2e80629a in free_line_header ()
#3  0x000055bf2e8079b2 in read_line_info ()
#4  0x000055bf2e8091e6 in dwarf_lookup_pc ()
#5  0x000055bf2e80989b in dwarf_fileline ()
#6  0x000055bf2e7f8f0c in backtrace_pcinfo ()
#7  0x000055bf2c9279a6 in boost::stacktrace::detail::to_string_using_backtrace::prepare_function_name (addr=0x55bf2c923ee8 <doris::signal::(anonymous namespace)::FailureSignalHandler(int, siginfo_t*, void*)+7096>, this=0x7bfa3f6a1780)
    at /var/local/thirdparty/installed/include/boost/stacktrace/detail/libbacktrace_impls.hpp:123
#8  boost::stacktrace::detail::to_string_impl_base<boost::stacktrace::detail::to_string_using_backtrace>::operator()[abi:cxx11](void const*) (
    addr=0x55bf2c923ee8 <doris::signal::(anonymous namespace)::FailureSignalHandler(int, siginfo_t*, void*)+7096>, this=0x7bfa3f6a1780) at /var/local/thirdparty/installed/include/boost/stacktrace/detail/frame_unwind.ipp:39
#9  boost::stacktrace::detail::to_string[abi:cxx11](boost::stacktrace::frame const*, unsigned long) (frames=<optimized out>, size=<optimized out>) at /var/local/thirdparty/installed/include/boost/stacktrace/detail/frame_unwind.ipp:76
#10 0x000055bf2c929d2d in boost::stacktrace::to_string<std::allocator<boost::stacktrace::frame> > (bt=...) at /var/local/ldb-toolchain/include/c++/11/bits/stl_vector.h:918
#11 boost::stacktrace::operator<< <char, std::char_traits<char>, std::allocator<boost::stacktrace::frame> > (os=..., bt=...) at /var/local/thirdparty/installed/include/boost/stacktrace/stacktrace.hpp:408
#12 0x000055bf2c923ef7 in doris::signal::(anonymous namespace)::FailureSignalHandler (signal_number=11, signal_info=<optimized out>, ucontext=<optimized out>) at /var/local/ldb-toolchain/include/c++/11/bits/stl_vector.h:97
#13 <signal handler called>
#14 0x000055bf2e801afb in backtrace_free_locked ()
#15 0x000055bf2e801dcb in backtrace_free ()
#16 0x000055bf2e80629a in free_line_header ()
#17 0x000055bf2e8079b2 in read_line_info ()
#18 0x000055bf2e8091e6 in dwarf_lookup_pc ()
#19 0x000055bf2e80989b in dwarf_fileline ()
#20 0x000055bf2e7f8f0c in backtrace_pcinfo ()
#21 0x000055bf2c9279a6 in boost::stacktrace::detail::to_string_using_backtrace::prepare_function_name (addr=0x55bf2cb07f2e <doris::FlushToken::_flush_memtable(std::shared_ptr<doris::MemTable>, long)+910>, this=0x7bfa3f6a2500)
    at /var/local/thirdparty/installed/include/boost/stacktrace/detail/libbacktrace_impls.hpp:123
#22 boost::stacktrace::detail::to_string_impl_base<boost::stacktrace::detail::to_string_using_backtrace>::operator()[abi:cxx11](void const*) (
    addr=0x55bf2cb07f2e <doris::FlushToken::_flush_memtable(std::shared_ptr<doris::MemTable>, long)+910>, this=0x7bfa3f6a2500) at /var/local/thirdparty/installed/include/boost/stacktrace/detail/frame_unwind.ipp:39
#23 boost::stacktrace::detail::to_string[abi:cxx11](boost::stacktrace::frame const*, unsigned long) (frames=<optimized out>, size=<optimized out>) at /var/local/thirdparty/installed/include/boost/stacktrace/detail/frame_unwind.ipp:76
#24 0x000055bf2c936d0c in boost::stacktrace::to_string<std::allocator<boost::stacktrace::frame> > (bt=...) at /var/local/ldb-toolchain/include/c++/11/bits/stl_vector.h:918
#25 doris::Status::ConstructErrorStatus (precise_code=precise_code@entry=-201, msg=...) at /root/doris-ldb-toolchain-latest-release/be/src/common/status.cpp:78
#26 0x000055bf2cbe6594 in doris::Status::OLAPInternalError (precise_code=-201) at /root/doris-ldb-toolchain-latest-release/be/src/util/slice.h:53
#27 doris::MemTable::flush (this=0x55c2a6f983c0) at /root/doris-ldb-toolchain-latest-release/be/src/olap/memtable.cpp:134
#28 0x000055bf2cb07f2e in doris::FlushToken::_flush_memtable (this=0x55c0bc580300, memtable=..., submit_task_time=52984257160372396) at /var/local/ldb-toolchain/include/c++/11/bits/shared_ptr_base.h:1290
#29 0x000055bf2cb08660 in std::__invoke_impl<void, void (doris::FlushToken::*&)(std::shared_ptr<doris::MemTable>, long), doris::FlushToken*&, std::shared_ptr<doris::MemTable>&, long&> (__f=<optimized out>, __t=<optimized out>,
    __f=<optimized out>, __t=<optimized out>) at /var/local/ldb-toolchain/include/c++/11/ext/atomicity.h:109
#30 std::__invoke<void (doris::FlushToken::*&)(std::shared_ptr<doris::MemTable>, long), doris::FlushToken*&, std::shared_ptr<doris::MemTable>&, long&> (__fn=<optimized out>) at /var/local/ldb-toolchain/include/c++/11/bits/invoke.h:96
#31 std::_Bind<void (doris::FlushToken::*(doris::FlushToken*, std::shared_ptr<doris::MemTable>, long))(std::shared_ptr<doris::MemTable>, long)>::__call<void, , 0ul, 1ul, 2ul>(std::tuple<>&&, std::_Index_tuple<0ul, 1ul, 2ul>) (
    __args=..., this=<optimized out>) at /var/local/ldb-toolchain/include/c++/11/functional:420
#32 std::_Bind<void (doris::FlushToken::*(doris::FlushToken*, std::shared_ptr<doris::MemTable>, long))(std::shared_ptr<doris::MemTable>, long)>::operator()<, void>() (this=<optimized out>)
    at /var/local/ldb-toolchain/include/c++/11/functional:503
#33 std::__invoke_impl<void, std::_Bind<void (doris::FlushToken::*(doris::FlushToken*, std::shared_ptr<doris::MemTable>, long))(std::shared_ptr<doris::MemTable>, long)>&>(std::__invoke_other, std::_Bind<void (doris::FlushToken::*(doris::FlushToken*, std::shared_ptr<doris::MemTable>, long))(std::shared_ptr<doris::MemTable>, long)>&) (__f=...) at /var/local/ldb-toolchain/include/c++/11/bits/invoke.h:61
#34 std::__invoke_r<void, std::_Bind<void (doris::FlushToken::*(doris::FlushToken*, std::shared_ptr<doris::MemTable>, long))(std::shared_ptr<doris::MemTable>, long)>&>(std::_Bind<void (doris::FlushToken::*(doris::FlushToken*, std::shared_ptr<doris::MemTable>, long))(std::shared_ptr<doris::MemTable>, long)>&) (__fn=...) at /var/local/ldb-toolchain/include/c++/11/bits/invoke.h:111
#35 std::_Function_handler<void (), std::_Bind<void (doris::FlushToken::*(doris::FlushToken*, std::shared_ptr<doris::MemTable>, long))(std::shared_ptr<doris::MemTable>, long)> >::_M_invoke(std::_Any_data const&) (__functor=...)
    at /var/local/ldb-toolchain/include/c++/11/bits/std_function.h:291

![image](https://user-images.githubusercontent.com/13197424/165060323-38b16e9c-6837-4612-b4dc-0918b91d3710.png)

### What You Expected?

run

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by xinyiZzz** [comment]
cc @yiguolei
