### ISSUE TITLE
[Bug] fe start faild (version:1.0.0-preview2)

### ISSUE THREAD

**Issue by PeterGZW** [apache/incubator-doris#9668]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-doris/issues?q=is%3Aissue) and found no similar issues.

### Version

1.0.0-preview2

### What's Wrong?

fe start faild.  
----------------------
2022-05-18 15:28:41,121 INFO (main|1) [MetaReader.read():70] start load image from /doris/incubator-doris/fe/doris-meta/image/image.13556805. is ckpt: false
2022-05-18 15:28:41,122 WARN (main|1) [MetaHeader.read():58] Image file /doris/incubator-doris/fe/doris-meta/image/image.13527036 format mismatch. Expected magic number is [67, 79, 82, 49], actual is [0, 0, 0, 99]
2022-05-18 15:28:41,126 INFO (main|1) [Catalog.loadHeaderCOR1():1691] finished replay header from image
2022-05-18 15:28:41,127 INFO (main|1) [Catalog.loadMasterInfo():1702] finished replay masterInfo from image
java.lang.IllegalArgumentException: No enum constant org.apache.doris.catalog.PrimitiveType.DECIMAL
        at java.lang.Enum.valueOf(Enum.java:238)
        at org.apache.doris.catalog.PrimitiveType.valueOf(PrimitiveType.java:30)
        at org.apache.doris.catalog.ColumnType.read(ColumnType.java:141)
        at org.apache.doris.catalog.Function.readFields(Function.java:652)
        at org.apache.doris.catalog.ScalarFunction.readFields(ScalarFunction.java:386)
        at org.apache.doris.catalog.Function.read(Function.java:688)
        at org.apache.doris.catalog.Database.readFields(Database.java:677)
        at org.apache.doris.catalog.Catalog.loadDb(Catalog.java:1736)
        at org.apache.doris.common.MetaReader.read(MetaReader.java:81)
        at org.apache.doris.catalog.Catalog.loadImage(Catalog.java:1621)
        at org.apache.doris.catalog.Catalog.initialize(Catalog.java:851)
        at org.apache.doris.PaloFe.start(PaloFe.java:125)
        at org.apache.doris.PaloFe.main(PaloFe.java:63)

### What You Expected?

fe start success.

### How to Reproduce?

fe version  0.15.1 upgrade to 1.0.0 start faild. Replaced all files.
image download url:  https://www.bizgo.com/temp/image.13556805

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by hf200012** [comment]
@PeterGZW Please add me WeChat, this problem I will solve this problem for you, WeChat: 35926237
